// ───────────────────────────────────────────────────────────────────────────
// ERZEUGT von scripts/katalog-erzeugen.mjs aus
// apps/multicam-planner/src/data/cameras.ts — NICHT von Hand aendern.
//
// Hier steht nur die IDENTITAET eines Kameramodells: Id, Hersteller, Modell,
// Kategorie, Datenblatt. Die fachlichen Fakten (Sensor, Bajonett,
// Aufloesungen, Sensormodi) bleiben im MultiCam-Planer — sie versteht sonst
// niemand, und ein Paket, das sie fuehrte, waere der MultiCam-Planer mit
// anderem Namen.
//
// `npm run katalog:parity` besteht darauf, dass diese Datei noch aus jener
// stammt.
// ───────────────────────────────────────────────────────────────────────────
import type { TypEingabe } from './typ'

/** 377 Kameramodelle. */
export const KAMERA_TYPEN: readonly TypEingabe[] = [
  { id: "abgeleitet:sony:hdc-3500", hersteller: "Sony", modell: "HDC-3500", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-3500" },
  { id: "abgeleitet:sony:hdc-5500", hersteller: "Sony", modell: "HDC-5500", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-5500" },
  { id: "abgeleitet:sony:hdc-f5500", hersteller: "Sony", modell: "HDC-F5500", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-f5500" },
  { id: "abgeleitet:sony:venice", hersteller: "Sony", modell: "VENICE", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/digital-cinema-cameras/venice" },
  { id: "abgeleitet:sony:venice-2", hersteller: "Sony", modell: "VENICE 2", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/digital-cinema-cameras/venice2" },
  { id: "f54cdfa3-1708-4b05-9179-4a8769c0b891", hersteller: "Sony", modell: "PMW-F5", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/digital-cinema-cameras/pmw-f5" },
  { id: "eb02ca7e-856c-40ab-9a73-d1e98110f003", hersteller: "Sony", modell: "PMW-F55", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/digital-cinema-cameras/pmw-f55" },
  { id: "a823f2ff-3be9-4c45-af4e-bd4f6b13f7d7", hersteller: "Sony", modell: "FX6", kategorie: 'Cameras', datenblattUrl: "https://sony-mea.com/en/electronics/professional-video-cameras/ilme-fx6/specifications" },
  { id: "3cd5dd2d-7d51-4af9-ad59-25860aa4baa2", hersteller: "Sony", modell: "FX3", kategorie: 'Cameras', datenblattUrl: "https://www.sony-asia.com/electronics/support/camcorders-interchangeable-lens-camcorders/ilme-fx3/specifications" },
  { id: "05d88e97-2f3d-4b16-868c-f13f202754c5", hersteller: "Sony", modell: "PXW-FX9", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/handheld-camcorders/pxw-fx9" },
  { id: "ff69e6b9-7a72-4eb2-ba53-df17fd8bfdf7", hersteller: "Sony", modell: "PXW-FS7 II", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/handheld-camcorders/pxw-fs7m2" },
  { id: "abgeleitet:sony:a7s-iii", hersteller: "Sony", modell: "A7S III", kategorie: 'Cameras', datenblattUrl: "https://www.sony.co.uk/electronics/support/e-mount-body-ilce-7-series/ilce-7sm3/specifications" },
  { id: "abgeleitet:sony:a7-iv", hersteller: "Sony", modell: "A7 IV", kategorie: 'Cameras', datenblattUrl: "https://www.sony-asia.com/interchangeable-lens-cameras/products/ilce-7m4" },
  { id: "abgeleitet:sony:fr7", hersteller: "Sony", modell: "FR7", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/en_CO/products/ptz-network-cameras/ilme-fr7" },
  { id: "abgeleitet:sony:pdw-700", hersteller: "Sony", modell: "PDW-700", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/shoulder-camcorders/pdw-700" },
  { id: "abgeleitet:sony:pdw-850", hersteller: "Sony", modell: "PDW-850", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/shoulder-camcorders/pdw-850" },
  { id: "abgeleitet:sony:pdw-f800", hersteller: "Sony", modell: "PDW-F800", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/shoulder-camcorders/pdw-f800" },
  { id: "abgeleitet:sony:hdc-4300", hersteller: "Sony", modell: "HDC-4300", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-4300" },
  { id: "abgeleitet:sony:brc-x400", hersteller: "Sony", modell: "BRC-X400", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/ptz-network-cameras/brc-x400" },
  { id: "abgeleitet:sony:srg-x120", hersteller: "Sony", modell: "SRG-X120", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/ptz-network-cameras/srg-x120" },
  { id: "abgeleitet:sony:brc-h800", hersteller: "Sony", modell: "BRC-H800", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/ptz-network-cameras/brc-h800" },
  { id: "87fc07c8-7327-466d-9fd1-eac259af154e", hersteller: "Canon", modell: "C500 Mark II", kategorie: 'Cameras', datenblattUrl: "https://www.canon-europe.com/video-cameras/eos-c500-mark-ii/specifications/" },
  { id: "bfdc4077-32b8-4f1b-b9a5-6f875b37816c", hersteller: "Canon", modell: "C300 Mark III", kategorie: 'Cameras', datenblattUrl: "https://www.canon-europe.com/video-cameras/eos-c300-mark-iii/specifications/" },
  { id: "fd8fdb1a-0927-4d70-9c8b-f40ef5ef0fdb", hersteller: "Canon", modell: "C70", kategorie: 'Cameras', datenblattUrl: "https://www.canon-europe.com/video-cameras/eos-c70/specifications/" },
  { id: "abgeleitet:canon:xf605", hersteller: "Canon", modell: "XF605", kategorie: 'Cameras', datenblattUrl: "https://www.canon-europe.com/video-cameras/xf605/specifications/" },
  { id: "abgeleitet:canon:cr-n500", hersteller: "Canon", modell: "CR-N500", kategorie: 'Cameras', datenblattUrl: "https://www.canon-europe.com/ptz-cameras/cr-n500/specifications/" },
  { id: "abgeleitet:canon:cr-n300", hersteller: "Canon", modell: "CR-N300", kategorie: 'Cameras', datenblattUrl: "https://www.canon-europe.com/ptz-cameras/cr-n300/specifications/" },
  { id: "abgeleitet:panasonic:ak-uc4000", hersteller: "Panasonic", modell: "AK-UC4000", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/ak-uc4000/spec.html" },
  { id: "abgeleitet:panasonic:ak-uc3300", hersteller: "Panasonic", modell: "AK-UC3300", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/ak-uc3300/spec.html" },
  { id: "abgeleitet:panasonic:ak-hc5000", hersteller: "Panasonic", modell: "AK-HC5000", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/ak-hc5000/spec.html" },
  { id: "abgeleitet:panasonic:au-eva1", hersteller: "Panasonic", modell: "AU-EVA1", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/products/eva1/" },
  { id: "abgeleitet:panasonic:aw-ue150", hersteller: "Panasonic", modell: "AW-UE150", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-ue150/spec.html" },
  { id: "abgeleitet:blackmagic:ursa-broadcast-g2", hersteller: "Blackmagic", modell: "URSA Broadcast G2", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicursabroadcast/techspecs" },
  { id: "1b94e2d9-f987-4b76-8827-f555d88a2e10", hersteller: "Blackmagic", modell: "URSA Mini Pro 12K", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicursaminipro/techspecs/W-URSA-36" },
  { id: "abgeleitet:blackmagic:ursa-mini-pro-g2", hersteller: "Blackmagic", modell: "URSA Mini Pro G2", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicursaminipro/techspecs/W-URSA-34" },
  { id: "abgeleitet:blackmagic:ursa-mini-pro-4-6k", hersteller: "Blackmagic", modell: "URSA Mini Pro 4.6K", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/media/release/20170302-01" },
  { id: "abgeleitet:blackmagic:pocket-cinema-6k-pro", hersteller: "Blackmagic", modell: "Pocket Cinema 6K Pro", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicpocketcinemacamera/techspecs" },
  { id: "abgeleitet:blackmagic:pocket-cinema-6k-g2", hersteller: "Blackmagic", modell: "Pocket Cinema 6K G2", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicpocketcinemacamera/techspecs/W-CIN-19" },
  { id: "abgeleitet:blackmagic:pocket-cinema-4k", hersteller: "Blackmagic", modell: "Pocket Cinema 4K", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicpocketcinemacamera/techspecs/W-CIN-12" },
  { id: "abgeleitet:blackmagic:cinema-camera-6k", hersteller: "Blackmagic", modell: "Cinema Camera 6K", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagiccinemacamera/techspecs" },
  { id: "abgeleitet:blackmagic:pyxis-6k", hersteller: "Blackmagic", modell: "PYXIS 6K", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicpyxis/techspecs" },
  { id: "abgeleitet:blackmagic:studio-camera-4k-plus", hersteller: "Blackmagic", modell: "Studio Camera 4K Plus", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicstudiocamera" },
  { id: "ca069b86-a1ce-438e-a390-28c3445254c0", hersteller: "Blackmagic", modell: "Studio Camera 4K Pro G2", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicstudiocamera/techspecs/W-CST-12" },
  { id: "abgeleitet:blackmagic:studio-camera-6k-pro", hersteller: "Blackmagic", modell: "Studio Camera 6K Pro", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicstudiocamera/techspecs/W-CST-11" },
  { id: "abgeleitet:blackmagic:micro-studio-camera-4k-g2", hersteller: "Blackmagic", modell: "Micro Studio Camera 4K G2", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicmicrostudiocamera/techspecs" },
  { id: "abgeleitet:grass-valley:ldx-100", hersteller: "Grass Valley", modell: "LDX 100", kategorie: 'Cameras', datenblattUrl: "https://www.grassvalley.com/ldx-100/" },
  { id: "abgeleitet:grass-valley:ldx-150", hersteller: "Grass Valley", modell: "LDX 150", kategorie: 'Cameras', datenblattUrl: "https://www.grassvalley.com/products/cameras/ldx-100-series/ldx-150/" },
  { id: "abgeleitet:hitachi:sk-hd1800", hersteller: "Hitachi", modell: "SK-HD1800", kategorie: 'Cameras', datenblattUrl: "https://www.hitachi-kokusai.co.jp/global/en/products/broadcast/camera/hd/sk-hd1800/sk-hd1800_f.html" },
  { id: "abgeleitet:hitachi:sk-uhd7000", hersteller: "Hitachi", modell: "SK-UHD7000", kategorie: 'Cameras', datenblattUrl: "https://www.kokusaidenki.co.jp/kde/global/en/products/broadcast/download/pdf/SK-UHD7000_CU-UHD7000.pdf" },
  { id: "abgeleitet:arri:alexa-35", hersteller: "ARRI", modell: "ALEXA 35", kategorie: 'Cameras', datenblattUrl: "https://www.arri.com/en/camera-systems/cameras/alexa-35" },
  { id: "abgeleitet:arri:amira", hersteller: "ARRI", modell: "AMIRA", kategorie: 'Cameras', datenblattUrl: "https://www.arri.com/en/camera-systems/cameras/amira" },
  { id: "abgeleitet:red:v-raptor-xl", hersteller: "RED", modell: "V-RAPTOR XL", kategorie: 'Cameras', datenblattUrl: "https://www.reddigitalcinema.com/v-raptor-xl" },
  { id: "abgeleitet:red:komodo-6k", hersteller: "RED", modell: "KOMODO 6K", kategorie: 'Cameras', datenblattUrl: "https://www.reddigitalcinema.com/komodo" },
  { id: "abgeleitet:red:komodo-x-6k", hersteller: "RED", modell: "KOMODO-X 6K", kategorie: 'Cameras', datenblattUrl: "https://www.reddigitalcinema.com/komodo-x" },
  { id: "abgeleitet:arri:alexa-mini-lf", hersteller: "ARRI", modell: "ALEXA Mini LF", kategorie: 'Cameras', datenblattUrl: "https://www.arri.com/en/camera-systems/cameras/alexa-mini-lf" },
  { id: "abgeleitet:sony:burano", hersteller: "Sony", modell: "BURANO", kategorie: 'Cameras', datenblattUrl: "https://sony-cinematography.com/burano/" },
  { id: "abgeleitet:panasonic:bs1h", hersteller: "Panasonic", modell: "BS1H", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/products/bs1h/index.html" },
  { id: "abgeleitet:z-cam:e2", hersteller: "Z CAM", modell: "E2", kategorie: 'Cameras', datenblattUrl: "https://www.z-cam.com/products/professional-cameras/e2/" },
  { id: "abgeleitet:z-cam:e2c", hersteller: "Z CAM", modell: "E2C", kategorie: 'Cameras', datenblattUrl: "https://www.z-cam.com/products/professional-cameras/e2c/" },
  { id: "abgeleitet:z-cam:e2-m4", hersteller: "Z CAM", modell: "E2-M4", kategorie: 'Cameras', datenblattUrl: "https://www.z-cam.com/products/professional-cameras/e2-m4/" },
  { id: "abgeleitet:z-cam:e2-s6", hersteller: "Z CAM", modell: "E2-S6", kategorie: 'Cameras', datenblattUrl: "https://www.z-cam.com/products/professional-cameras/e2-s6/" },
  { id: "abgeleitet:z-cam:e2-f6", hersteller: "Z CAM", modell: "E2-F6", kategorie: 'Cameras', datenblattUrl: "https://www.z-cam.com/e2-f6/" },
  { id: "abgeleitet:z-cam:e2-f8", hersteller: "Z CAM", modell: "E2-F8", kategorie: 'Cameras', datenblattUrl: "https://www.z-cam.com/products/professional-cameras/e2-f8/" },
  { id: "abgeleitet:z-cam:e2-s6-mark-ii", hersteller: "Z CAM", modell: "E2-S6 Mark II", kategorie: 'Cameras', datenblattUrl: "https://www.z-cam.com/products/professional-cameras/e2-mkii/" },
  { id: "abgeleitet:z-cam:e2-f8-mark-ii", hersteller: "Z CAM", modell: "E2-F8 Mark II", kategorie: 'Cameras', datenblattUrl: "https://www.z-cam.com/products/professional-cameras/e2-mkii/" },
  { id: "abgeleitet:ikegami:uhk-430", hersteller: "Ikegami", modell: "UHK-430", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.com/product/detail/765/" },
  { id: "abgeleitet:ikegami:uhk-x700", hersteller: "Ikegami", modell: "UHK-X700", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.com/product/detail/763/" },
  { id: "abgeleitet:ikegami:uhk-x600", hersteller: "Ikegami", modell: "UHK-X600", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.com/product/detail/767/" },
  { id: "abgeleitet:ikegami:uhl-43", hersteller: "Ikegami", modell: "UHL-43", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.com/product/detail/772/" },
  { id: "abgeleitet:ikegami:hdk-99", hersteller: "Ikegami", modell: "HDK-99", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.com/product/detail/769/" },
  { id: "abgeleitet:ikegami:hdk-73", hersteller: "Ikegami", modell: "HDK-73", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.de/hdk-73.html" },
  { id: "abgeleitet:ikegami:hdk-55", hersteller: "Ikegami", modell: "HDK-55", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.com/product/detail/1031/" },
  { id: "abgeleitet:ikegami:hdk-97arri", hersteller: "Ikegami", modell: "HDK-97ARRI", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.com/product/detail/1013/" },
  { id: "abgeleitet:panasonic:ak-uc3000", hersteller: "Panasonic", modell: "AK-UC3000", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/ak-uc3000" },
  { id: "abgeleitet:panasonic:ak-hc3900", hersteller: "Panasonic", modell: "AK-HC3900", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/ak-hc3900" },
  { id: "abgeleitet:panasonic:ak-hc3800", hersteller: "Panasonic", modell: "AK-HC3800", kategorie: 'Cameras', datenblattUrl: "https://na.panasonic.com/ns/22267_AK-HC3800_Brochure_PDF_V1.pdf" },
  { id: "abgeleitet:sony:hdc-3200", hersteller: "Sony", modell: "HDC-3200", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-3200" },
  { id: "abgeleitet:sony:hdc-3170", hersteller: "Sony", modell: "HDC-3170", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-3170" },
  { id: "abgeleitet:sony:hdc-3100", hersteller: "Sony", modell: "HDC-3100", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-3100" },
  { id: "abgeleitet:sony:hxc-fb80", hersteller: "Sony", modell: "HXC-FB80", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hxc-fb80" },
  { id: "abgeleitet:sony:hsc-100", hersteller: "Sony", modell: "HSC-100", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hsc-100r" },
  { id: "abgeleitet:sony:pxw-z750", hersteller: "Sony", modell: "PXW-Z750", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/shoulder-camcorders/pxw-z750" },
  { id: "abgeleitet:sony:pxw-z450", hersteller: "Sony", modell: "PXW-Z450", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/shoulder-camcorders/pxw-z450" },
  { id: "abgeleitet:grass-valley:ldx-135", hersteller: "Grass Valley", modell: "LDX 135", kategorie: 'Cameras', datenblattUrl: "https://www.grassvalley.com/products/cameras/ldx-100-series/ldx-135/" },
  { id: "abgeleitet:grass-valley:ldx-98", hersteller: "Grass Valley", modell: "LDX 98", kategorie: 'Cameras', datenblattUrl: "https://www.grassvalley.com/products/cameras/ldx-90-series-family/ldx-98/" },
  { id: "abgeleitet:grass-valley:ldx-86n", hersteller: "Grass Valley", modell: "LDX 86N", kategorie: 'Cameras', datenblattUrl: "https://wwwapps.grassvalley.com/docs/DataSheets/cameras/ldx/LDX_Series_DS-PUB-2-0161F-EN.pdf" },
  { id: "abgeleitet:hitachi:sk-hd1500", hersteller: "Hitachi", modell: "SK-HD1500", kategorie: 'Cameras', datenblattUrl: "https://www.hitachi-kokusai.co.jp/global/en/products/broadcast/camera/discontinued_products/sk-hd1500/index.html" },
  { id: "abgeleitet:hitachi:z-hd6500", hersteller: "Hitachi", modell: "Z-HD6500", kategorie: 'Cameras', datenblattUrl: "https://www.kokusaidenki.co.jp/global/en/products/broadcast/camera/hd/z-hd6500/index.html" },
  { id: "abgeleitet:hitachi:sk-uhd4000b", hersteller: "Hitachi", modell: "SK-UHD4000B", kategorie: 'Cameras', datenblattUrl: "https://www.hitachi-kokusai.co.jp/global/en/products/broadcast/camera/sk-uhd4000/index.html" },
  { id: "abgeleitet:panasonic:varicam-lt", hersteller: "Panasonic", modell: "VariCam LT", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/products/varicam_lt/" },
  { id: "abgeleitet:panasonic:varicam-35", hersteller: "Panasonic", modell: "VariCam 35", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/products/varicam_35/" },
  { id: "abgeleitet:panasonic:lumix-s1h", hersteller: "Panasonic", modell: "Lumix S1H", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/products/s1h/index.html" },
  { id: "abgeleitet:panasonic:lumix-gh6", hersteller: "Panasonic", modell: "Lumix GH6", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/specifications-sheet-for-lumix-g-series-dc-gh6/" },
  { id: "abgeleitet:panasonic:lumix-gh7", hersteller: "Panasonic", modell: "Lumix GH7", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/features-and-specifications-lumix-g-series-model-dc-gh7/" },
  { id: "abgeleitet:panasonic:lumix-bgh1", hersteller: "Panasonic", modell: "Lumix BGH1", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/cinema_camera_varicam_eva/products/bgh1/index.html" },
  { id: "abgeleitet:kinefinity:mavo-edge-8k", hersteller: "Kinefinity", modell: "MAVO Edge 8K", kategorie: 'Cameras', datenblattUrl: "https://kinefinity.com/mavo-edge-2/" },
  { id: "abgeleitet:kinefinity:mavo-edge-6k", hersteller: "Kinefinity", modell: "MAVO Edge 6K", kategorie: 'Cameras', datenblattUrl: "https://kinefinity.com/mavo-edge-6k/" },
  { id: "abgeleitet:kinefinity:mavo-lf", hersteller: "Kinefinity", modell: "MAVO LF", kategorie: 'Cameras', datenblattUrl: "https://kinefinity.com/mavo-mark2-camera/" },
  { id: "abgeleitet:kinefinity:mavo-s35", hersteller: "Kinefinity", modell: "MAVO S35", kategorie: 'Cameras', datenblattUrl: "https://kinefinity.com/mavo-mark2-camera/" },
  { id: "abgeleitet:panasonic:aw-ue160", hersteller: "Panasonic", modell: "AW-UE160", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-ue160/spec.html" },
  { id: "abgeleitet:panasonic:aw-ue100", hersteller: "Panasonic", modell: "AW-UE100", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-ue100/spec.html" },
  { id: "abgeleitet:sony:brc-x1000", hersteller: "Sony", modell: "BRC-X1000", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/ptz-network-cameras/brc-x1000" },
  { id: "abgeleitet:sony:srg-x400", hersteller: "Sony", modell: "SRG-X400", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/ptz-network-cameras/srg-x400" },
  { id: "abgeleitet:canon:cr-n700", hersteller: "Canon", modell: "CR-N700", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/business/cr-n700/main/specification" },
  { id: "abgeleitet:canon:eos-c400", hersteller: "Canon", modell: "EOS C400", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/consumer/eos-c400/specification" },
  { id: "abgeleitet:canon:eos-c80", hersteller: "Canon", modell: "EOS C80", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/consumer/eos-c80/specification" },
  { id: "abgeleitet:red:v-raptor-8k-vv", hersteller: "RED", modell: "V-RAPTOR 8K VV", kategorie: 'Cameras', datenblattUrl: "https://www.red.com/v-raptor" },
  { id: "abgeleitet:red:v-raptor-8k-s35", hersteller: "RED", modell: "V-RAPTOR 8K S35", kategorie: 'Cameras', datenblattUrl: "https://www.red.com/v-raptor" },
  { id: "abgeleitet:red:v-raptor-xl-8k-s35", hersteller: "RED", modell: "V-RAPTOR XL 8K S35", kategorie: 'Cameras', datenblattUrl: "https://www.red.com/v-raptor-xl" },
  { id: "abgeleitet:red:v-raptor-x-8k-vv", hersteller: "RED", modell: "V-RAPTOR [X] 8K VV", kategorie: 'Cameras', datenblattUrl: "https://www.red.com/v-raptor-x" },
  { id: "abgeleitet:blackmagic:ursa-cine-12k-lf", hersteller: "Blackmagic", modell: "URSA Cine 12K LF", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicursacine" },
  { id: "abgeleitet:arri:alexa-lf", hersteller: "ARRI", modell: "ALEXA LF", kategorie: 'Cameras', datenblattUrl: "https://www.arri.com/en/camera-systems/cameras/alexa-lf" },
  { id: "abgeleitet:canon:xf705", hersteller: "Canon", modell: "XF705", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/consumer/xf705/specification" },
  { id: "abgeleitet:canon:xa75", hersteller: "Canon", modell: "XA75", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/consumer/xa75/specification" },
  { id: "abgeleitet:sony:pxw-z190", hersteller: "Sony", modell: "PXW-Z190", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/handheld-camcorders/pxw-z190" },
  { id: "abgeleitet:sony:hxr-nx5r", hersteller: "Sony", modell: "HXR-NX5R", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/handheld-camcorders/hxr-nx5r" },
  { id: "abgeleitet:sony:pxw-fx30", hersteller: "Sony", modell: "PXW-FX30", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/handheld-camcorders/ilme-fx30" },
  { id: "abgeleitet:jvc:gy-hc900", hersteller: "JVC", modell: "GY-HC900", kategorie: 'Cameras', datenblattUrl: "https://www.jvc.com/usa/pro/professional-video/shoulder-cameras/gy-hc900chu/" },
  { id: "abgeleitet:jvc:gy-hc550", hersteller: "JVC", modell: "GY-HC550", kategorie: 'Cameras', datenblattUrl: "https://www.jvc.com/usa/pro/professional-video/handheld-cameras/gy-hc550u/" },
  { id: "abgeleitet:panasonic:ag-cx350", hersteller: "Panasonic", modell: "AG-CX350", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/ag-cx350/spec.html" },
  { id: "abgeleitet:canon:cr-n100", hersteller: "Canon", modell: "CR-N100", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/business/cr-n100/main/specification" },
  { id: "abgeleitet:panasonic:aw-ue80", hersteller: "Panasonic", modell: "AW-UE80", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-ue80/spec.html" },
  { id: "abgeleitet:panasonic:aw-ue50", hersteller: "Panasonic", modell: "AW-UE50", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-ue50-40/spec.html" },
  { id: "abgeleitet:panasonic:aw-he145", hersteller: "Panasonic", modell: "AW-HE145", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-he145/spec.html" },
  { id: "abgeleitet:sony:srg-a40", hersteller: "Sony", modell: "SRG-A40", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/ptz-network-cameras/srg-a40" },
  { id: "abgeleitet:ptzoptics:move-4k", hersteller: "PTZOptics", modell: "Move 4K", kategorie: 'Cameras', datenblattUrl: "https://www.ptzoptics.com/move-4k/" },
  { id: "abgeleitet:marshall:cv730", hersteller: "Marshall", modell: "CV730", kategorie: 'Cameras', datenblattUrl: "https://www.marshall-usa.com/cameras/CV730/" },
  { id: "abgeleitet:marshall:cv420-cs", hersteller: "Marshall", modell: "CV420-CS", kategorie: 'Cameras', datenblattUrl: "https://www.marshall-usa.com/cameras/CV420-CS/" },
  { id: "abgeleitet:marshall:cv420e", hersteller: "Marshall", modell: "CV420e", kategorie: 'Cameras', datenblattUrl: "https://www.marshall-usa.com/cameras/CV420e/" },
  { id: "abgeleitet:marshall:cv506", hersteller: "Marshall", modell: "CV506", kategorie: 'Cameras', datenblattUrl: "https://www.marshall-usa.com/cameras/CV506/" },
  { id: "abgeleitet:marshall:cv612", hersteller: "Marshall", modell: "CV612", kategorie: 'Cameras', datenblattUrl: "https://www.marshall-usa.com/cameras/CV612-TBI-TWI/" },
  { id: "abgeleitet:lumens:vc-a71", hersteller: "Lumens", modell: "VC-A71", kategorie: 'Cameras', datenblattUrl: "https://www.mylumens.com/products/vc-a71" },
  { id: "abgeleitet:lumens:vc-a50p", hersteller: "Lumens", modell: "VC-A50P", kategorie: 'Cameras', datenblattUrl: "https://www.mylumens.com/products/vc-a50p" },
  { id: "abgeleitet:birddog:p400", hersteller: "BirdDog", modell: "P400", kategorie: 'Cameras', datenblattUrl: "https://bird-dog.tv/p400-overview/" },
  { id: "abgeleitet:birddog:x1", hersteller: "BirdDog", modell: "X1", kategorie: 'Cameras', datenblattUrl: "https://bird-dog.tv/x1-overview/" },
  { id: "abgeleitet:aver:tr313", hersteller: "AVer", modell: "TR313", kategorie: 'Cameras', datenblattUrl: "https://www.averusa.com/pro-av/downloads/datasheet-brochure/tr313-datasheet.pdf" },
  { id: "abgeleitet:aver:tr333", hersteller: "AVer", modell: "TR333", kategorie: 'Cameras', datenblattUrl: "https://www.averusa.com/products/ptz-camera/tr333" },
  { id: "abgeleitet:sony:srg-xp1", hersteller: "Sony", modell: "SRG-XP1", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/ptz-network-cameras/srg-xp1" },
  { id: "abgeleitet:panasonic:aw-ue20", hersteller: "Panasonic", modell: "AW-UE20", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-ue20/spec.html" },
  { id: "abgeleitet:ptzoptics:link-4k", hersteller: "PTZOptics", modell: "Link 4K", kategorie: 'Cameras', datenblattUrl: "https://www.ptzoptics.com/link-4k/" },
  { id: "abgeleitet:canon:eos-r5-c", hersteller: "Canon", modell: "EOS R5 C", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/consumer/eos-r5-c/specification" },
  { id: "abgeleitet:canon:eos-r5-mark-ii", hersteller: "Canon", modell: "EOS R5 Mark II", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/consumer/eos-r5-mark-ii/specification" },
  { id: "abgeleitet:canon:eos-r3", hersteller: "Canon", modell: "EOS R3", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/consumer/eos-r3-body/specification" },
  { id: "abgeleitet:canon:eos-r6-mark-ii", hersteller: "Canon", modell: "EOS R6 Mark II", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/consumer/eos-r6-mark-ii/specification" },
  { id: "abgeleitet:sony:a1", hersteller: "Sony", modell: "A1", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a1/specifications" },
  { id: "abgeleitet:sony:a7r-v", hersteller: "Sony", modell: "A7R V", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a7rv/specifications" },
  { id: "abgeleitet:sony:a9-iii", hersteller: "Sony", modell: "A9 III", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a9iii/specifications" },
  { id: "abgeleitet:panasonic:lumix-s5-ii", hersteller: "Panasonic", modell: "Lumix S5 II", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/specifications-sheet-lumix-s-series-dc-s5m2/" },
  { id: "abgeleitet:panasonic:lumix-s1", hersteller: "Panasonic", modell: "Lumix S1", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/features-and-specifications-lumix-s-series-model-dc-s1/" },
  { id: "abgeleitet:panasonic:lumix-gh5-ii", hersteller: "Panasonic", modell: "Lumix GH5 II", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/features-and-specifications-lumix-s-series-model-dc-gh5m2/" },
  { id: "abgeleitet:red:dsmc2-monstro-8k-vv", hersteller: "RED", modell: "DSMC2 Monstro 8K VV", kategorie: 'Cameras', datenblattUrl: "https://docs.red.com/955-0170/DSMC2MONSTROOperationGuide/en-us/Content/A_TechSpecs/Specs_DSMC2_MONSTRO.htm" },
  { id: "abgeleitet:red:dsmc2-helium-8k-s35", hersteller: "RED", modell: "DSMC2 Helium 8K S35", kategorie: 'Cameras', datenblattUrl: "https://docs.red.com/955-0171/DSMC2HELIUMOperationGuide/en-us/Content/A_TechSpecs/Specs_DSMC2_HELIUM.htm" },
  { id: "abgeleitet:red:dsmc2-gemini-5k-s35", hersteller: "RED", modell: "DSMC2 Gemini 5K S35", kategorie: 'Cameras', datenblattUrl: "https://docs.red.com/955-0172_v7.0/DSMC2GEMINIOperationGuide/Content/A_TechSpecs/Specs_DSMC2_GEMINI.htm" },
  { id: "abgeleitet:marshall:cv566", hersteller: "Marshall", modell: "CV566", kategorie: 'Cameras', datenblattUrl: "https://www.marshall-usa.com/cameras/CV566/" },
  { id: "abgeleitet:marshall:cv346", hersteller: "Marshall", modell: "CV346", kategorie: 'Cameras', datenblattUrl: "https://www.marshall-usa.com/cameras/CV346/" },
  { id: "abgeleitet:marshall:cv380-cs", hersteller: "Marshall", modell: "CV380-CS", kategorie: 'Cameras', datenblattUrl: "https://www.marshall-usa.com/cameras/CV380-CS/" },
  { id: "abgeleitet:nikon:z9", hersteller: "Nikon", modell: "Z9", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/z-9/1669/overview" },
  { id: "abgeleitet:nikon:z8", hersteller: "Nikon", modell: "Z8", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/z-8/1695/overview" },
  { id: "abgeleitet:nikon:z6-iii", hersteller: "Nikon", modell: "Z6 III", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/z6iii/1890/overview" },
  { id: "abgeleitet:nikon:zf", hersteller: "Nikon", modell: "Zf", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/z-f/1761/overview" },
  { id: "abgeleitet:sony:zv-e1", hersteller: "Sony", modell: "ZV-E1", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_zve1/specifications" },
  { id: "abgeleitet:sony:a7-iii", hersteller: "Sony", modell: "A7 III", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a7iii/specifications" },
  { id: "abgeleitet:sony:a6700", hersteller: "Sony", modell: "A6700", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a6700/specifications" },
  { id: "abgeleitet:sony:fx2", hersteller: "Sony", modell: "FX2", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_fx2/specifications" },
  { id: "abgeleitet:panasonic:lumix-s9", hersteller: "Panasonic", modell: "Lumix S9", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/features-and-specifications-lumix-s-series-model-dc-s9k/" },
  { id: "abgeleitet:sony:srg-a12", hersteller: "Sony", modell: "SRG-A12", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/ptz-network-cameras/srg-a12" },
  { id: "abgeleitet:panasonic:aw-he40", hersteller: "Panasonic", modell: "AW-HE40", kategorie: 'Cameras', datenblattUrl: "https://eu.connect.panasonic.com/gb/en/broadcast-proav/aw-he40s" },
  { id: "abgeleitet:ptzoptics:move-se", hersteller: "PTZOptics", modell: "Move SE", kategorie: 'Cameras', datenblattUrl: "https://ptzoptics.com/move-se/" },
  { id: "abgeleitet:lumens:vc-tr40", hersteller: "Lumens", modell: "VC-TR40", kategorie: 'Cameras', datenblattUrl: "https://www.mylumens.com/en/Products_detail/1082/VC-TR40-AI-Auto-Tracking-Camera" },
  { id: "abgeleitet:aver:tr311", hersteller: "AVer", modell: "TR311", kategorie: 'Cameras', datenblattUrl: "https://www.averusa.com/pro-av/downloads/datasheet-brochure/tr311-datasheet.pdf" },
  { id: "abgeleitet:sony:hdc-p50", hersteller: "Sony", modell: "HDC-P50", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-p50" },
  { id: "abgeleitet:sony:hxc-fz90", hersteller: "Sony", modell: "HXC-FZ90", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hxc-fz90" },
  { id: "abgeleitet:panasonic:ak-ub300", hersteller: "Panasonic", modell: "AK-UB300", kategorie: 'Cameras', datenblattUrl: "https://eu.connect.panasonic.com/gb/en/broadcast-proav/ak-ub300gj" },
  { id: "abgeleitet:grass-valley:ldx-82", hersteller: "Grass Valley", modell: "LDX 82", kategorie: 'Cameras', datenblattUrl: "https://community.grassvalley.com/a2mHt000002rAIu" },
  { id: "abgeleitet:hitachi:sk-uhd8060b", hersteller: "Hitachi", modell: "SK-UHD8060B", kategorie: 'Cameras', datenblattUrl: "https://www.hitachikokusai.us/BroadcastandProfessionalCameras/SK-UHD8060B.html" },
  { id: "abgeleitet:jvc:gy-hc500", hersteller: "JVC", modell: "GY-HC500", kategorie: 'Cameras', datenblattUrl: "https://www.jvc.com/usa/pro/professional-video/handheld-cameras/gy-hc500u/" },
  { id: "abgeleitet:jvc:gy-hm250", hersteller: "JVC", modell: "GY-HM250", kategorie: 'Cameras', datenblattUrl: "https://www.jvc.com/usa/pro/professional-video/handheld-cameras/gy-hm250u/" },
  { id: "abgeleitet:canon:xf400", hersteller: "Canon", modell: "XF400", kategorie: 'Cameras', datenblattUrl: "https://www.canon-europe.com/video-cameras/xf-405-and-xf-400/specifications/" },
  { id: "abgeleitet:sony:hdc-p31", hersteller: "Sony", modell: "HDC-P31", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-p31" },
  { id: "abgeleitet:sony:hdc-p43", hersteller: "Sony", modell: "HDC-P43", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-p43" },
  { id: "abgeleitet:panasonic:ak-plv100", hersteller: "Panasonic", modell: "AK-PLV100", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/ak-plv100gsj/spec.html" },
  { id: "abgeleitet:aver:ptz330", hersteller: "AVer", modell: "PTZ330", kategorie: 'Cameras', datenblattUrl: "https://presentation.aver.com/model/ptz330" },
  { id: "abgeleitet:lumens:vc-b30u", hersteller: "Lumens", modell: "VC-B30U", kategorie: 'Cameras', datenblattUrl: "https://www.mylumens.com/en/Products_detail/23/VC-B30U-Video-Conference-Camera" },
  { id: "abgeleitet:panasonic:aw-ue4", hersteller: "Panasonic", modell: "AW-UE4", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-ue4/spec.html" },
  { id: "abgeleitet:sony:a7c-ii", hersteller: "Sony", modell: "A7C II", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a7cii/specifications" },
  { id: "abgeleitet:sony:a7cr", hersteller: "Sony", modell: "A7CR", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a7cr/specifications" },
  { id: "abgeleitet:sony:a7r-iv", hersteller: "Sony", modell: "A7R IV", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a7riv/specifications" },
  { id: "abgeleitet:sony:a9-ii", hersteller: "Sony", modell: "A9 II", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a9ii/specifications" },
  { id: "abgeleitet:sony:a6400", hersteller: "Sony", modell: "A6400", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a6400/specifications" },
  { id: "abgeleitet:sony:a6600", hersteller: "Sony", modell: "A6600", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a6600/specifications" },
  { id: "abgeleitet:sony:zv-e10", hersteller: "Sony", modell: "ZV-E10", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_zve10/specifications" },
  { id: "abgeleitet:canon:eos-r", hersteller: "Canon", modell: "EOS R", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/dslr877.html" },
  { id: "abgeleitet:canon:eos-rp", hersteller: "Canon", modell: "EOS RP", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/dslr880.html" },
  { id: "abgeleitet:canon:eos-r6", hersteller: "Canon", modell: "EOS R6", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/dslr895.html" },
  { id: "abgeleitet:canon:eos-r7", hersteller: "Canon", modell: "EOS R7", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/dslr901.html" },
  { id: "abgeleitet:canon:eos-r8", hersteller: "Canon", modell: "EOS R8", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/dslr907.html" },
  { id: "abgeleitet:canon:eos-r10", hersteller: "Canon", modell: "EOS R10", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/dslr902.html" },
  { id: "abgeleitet:canon:eos-90d", hersteller: "Canon", modell: "EOS 90D", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/dslr887.html" },
  { id: "abgeleitet:canon:eos-1d-x-mark-iii", hersteller: "Canon", modell: "EOS-1D X Mark III", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/dslr891.html" },
  { id: "abgeleitet:nikon:z5", hersteller: "Nikon", modell: "Z5", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/z-5/1641/overview" },
  { id: "abgeleitet:nikon:z6-ii", hersteller: "Nikon", modell: "Z6 II", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/z-6ii/1659/overview" },
  { id: "abgeleitet:nikon:z7-ii", hersteller: "Nikon", modell: "Z7 II", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/z-7ii/1653/overview" },
  { id: "abgeleitet:nikon:z50-ii", hersteller: "Nikon", modell: "Z50 II", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/z50ii/1784/overview" },
  { id: "abgeleitet:nikon:z5-ii", hersteller: "Nikon", modell: "Z5 II", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/z5ii/2020/overview" },
  { id: "abgeleitet:nikon:d850", hersteller: "Nikon", modell: "D850", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/d850/1585/overview" },
  { id: "abgeleitet:panasonic:lumix-s5", hersteller: "Panasonic", modell: "Lumix S5", kategorie: 'Cameras', datenblattUrl: "https://shop.panasonic.com/products/s5-full-frame-mirrorless-camera-body" },
  { id: "abgeleitet:panasonic:lumix-s5-iix", hersteller: "Panasonic", modell: "Lumix S5 IIX", kategorie: 'Cameras', datenblattUrl: "https://shop.panasonic.com/products/s5m2x-full-frame-mirrorless-camera-body" },
  { id: "abgeleitet:panasonic:lumix-s1r-ii", hersteller: "Panasonic", modell: "Lumix S1R II", kategorie: 'Cameras', datenblattUrl: "https://shop.panasonic.com/products/lumix-s1rii-full-frame-mirrorless-digital-camera-dc-s1rm2" },
  { id: "abgeleitet:panasonic:lumix-g9-ii", hersteller: "Panasonic", modell: "Lumix G9 II", kategorie: 'Cameras', datenblattUrl: "https://shop.panasonic.com/products/g9m2-mirrorless-camera-body" },
  { id: "abgeleitet:panasonic:lumix-gh5", hersteller: "Panasonic", modell: "Lumix GH5", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/features-and-specifications-lumix-g-series-dc-gh5/" },
  { id: "abgeleitet:fujifilm:x-h2s", hersteller: "Fujifilm", modell: "X-H2S", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/x-h2s/specifications/" },
  { id: "abgeleitet:fujifilm:x-h2", hersteller: "Fujifilm", modell: "X-H2", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/x-h2/specifications/" },
  { id: "abgeleitet:fujifilm:x-t5", hersteller: "Fujifilm", modell: "X-T5", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/x-t5/specifications/" },
  { id: "abgeleitet:fujifilm:x-s20", hersteller: "Fujifilm", modell: "X-S20", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/x-s20/specifications/" },
  { id: "abgeleitet:fujifilm:gfx100-ii", hersteller: "Fujifilm", modell: "GFX100 II", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/gfx100-ii/specifications/" },
  { id: "abgeleitet:fujifilm:gfx100s", hersteller: "Fujifilm", modell: "GFX100S", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/gfx100s/specifications/" },
  { id: "abgeleitet:blackmagic:pyxis-12k", hersteller: "Blackmagic", modell: "PYXIS 12K", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagicpyxis/techspecs" },
  { id: "abgeleitet:nikon:zr-red-cinema", hersteller: "Nikon", modell: "ZR (RED-Cinema)", kategorie: 'Cameras', datenblattUrl: "https://www.nikonusa.com/p/zr/2006/overview" },
  { id: "abgeleitet:sony:a7s-ii", hersteller: "Sony", modell: "A7S II", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a7sii/specifications" },
  { id: "abgeleitet:sony:a99-ii", hersteller: "Sony", modell: "A99 II", kategorie: 'Cameras', datenblattUrl: "https://en.wikipedia.org/wiki/Sony_%CE%B199_II" },
  { id: "abgeleitet:panasonic:lumix-gh4", hersteller: "Panasonic", modell: "Lumix GH4", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/features-and-specifications-lumix-g-series-dmc-gh4/" },
  { id: "abgeleitet:panasonic:lumix-s1r", hersteller: "Panasonic", modell: "Lumix S1R", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/features-and-specifications-lumix-s-series-model-dc-s1r/" },
  { id: "abgeleitet:om-system:om-1-mark-ii", hersteller: "OM System", modell: "OM-1 Mark II", kategorie: 'Cameras', datenblattUrl: "https://explore.omsystem.com/c/en/om-1-mark-ii" },
  { id: "abgeleitet:om-system:om-5", hersteller: "OM System", modell: "OM-5", kategorie: 'Cameras', datenblattUrl: "https://explore.omsystem.com/c/en/om-5-body-black" },
  { id: "abgeleitet:sony:hxc-100", hersteller: "Sony", modell: "HXC-100", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/en_AE/pdf/hxc-100" },
  { id: "abgeleitet:grass-valley:ldx-92", hersteller: "Grass Valley", modell: "LDX 92", kategorie: 'Cameras', datenblattUrl: "https://www.grassvalley.com/products/cameras/ldx-90-series-family/ldx-92/" },
  { id: "abgeleitet:hitachi:sk-hd1200", hersteller: "Hitachi", modell: "SK-HD1200", kategorie: 'Cameras', datenblattUrl: "https://www.hitachi-kokusai.co.jp/global/en/products/broadcast/camera/hd/sk-hd1200/sk-hd1200_f.html" },
  { id: "abgeleitet:ikegami:hdk-79ex-iii", hersteller: "Ikegami", modell: "HDK-79EX III", kategorie: 'Cameras', datenblattUrl: "https://www.bhphotovideo.com/c/product/741773-REG/Ikegami_HDK_79EXIII_CT9_HDK_79EXIII_CT9_Full_Digital_HDTV.html" },
  { id: "abgeleitet:panasonic:aw-ur100", hersteller: "Panasonic", modell: "AW-UR100", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-ur100/spec.html" },
  { id: "abgeleitet:sony:brc-h900", hersteller: "Sony", modell: "BRC-H900", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/ptz-network-cameras/brc-h900" },
  { id: "abgeleitet:canon:cr-x500", hersteller: "Canon", modell: "CR-X500", kategorie: 'Cameras', datenblattUrl: "https://www.canon-europe.com/ptz-cameras/cr-x500/specifications/" },
  { id: "abgeleitet:vaddio:roboshot-40-uhd", hersteller: "Vaddio", modell: "RoboSHOT 40 UHD", kategorie: 'Cameras', datenblattUrl: "https://www.legrandav.com/products/cameras/4k_ptz_camera/roboshot-40-uhd" },
  { id: "abgeleitet:panasonic:aw-he42", hersteller: "Panasonic", modell: "AW-HE42", kategorie: 'Cameras', datenblattUrl: "https://eu.connect.panasonic.com/gb/en/broadcast-proav/aw-he42" },
  { id: "abgeleitet:birddog:a300", hersteller: "BirdDog", modell: "A300", kategorie: 'Cameras', datenblattUrl: "https://birddog.tv/a300-overview/a300-techspecs/" },
  { id: "abgeleitet:ptzoptics:move-4k-30x", hersteller: "PTZOptics", modell: "Move 4K 30x", kategorie: 'Cameras', datenblattUrl: "https://ptzoptics.com/ptz-cameras/move-4k-30x" },
  { id: "abgeleitet:marshall:cv355-10x", hersteller: "Marshall", modell: "CV355-10X", kategorie: 'Cameras', datenblattUrl: "https://marshall-usa.com/cameras/CV355-10X/" },
  { id: "abgeleitet:marshall:cv503", hersteller: "Marshall", modell: "CV503", kategorie: 'Cameras', datenblattUrl: "https://marshall-usa.com/cameras/CV503/" },
  { id: "abgeleitet:marshall:cv225-m2", hersteller: "Marshall", modell: "CV225-M2", kategorie: 'Cameras', datenblattUrl: "https://marshall-usa.com/discontinued/cameras/CV225-MB.php" },
  { id: "abgeleitet:marshall:cv605", hersteller: "Marshall", modell: "CV605", kategorie: 'Cameras', datenblattUrl: "https://marshall-usa.com/cameras/CV605-BK-WH/" },
  { id: "abgeleitet:gopro:hero12-black", hersteller: "GoPro", modell: "HERO12 Black", kategorie: 'Cameras', datenblattUrl: "https://gopro.com/en/us/shop/cameras/hero12-black/CHDHX-121-master.html" },
  { id: "abgeleitet:gopro:hero13-black", hersteller: "GoPro", modell: "HERO13 Black", kategorie: 'Cameras', datenblattUrl: "https://gopro.com/en/us/shop/cameras/learn/hero13black/CHDHX-131-master.html" },
  { id: "abgeleitet:dji:osmo-action-4", hersteller: "DJI", modell: "Osmo Action 4", kategorie: 'Cameras', datenblattUrl: "https://www.dji.com/osmo-action-4/specs" },
  { id: "abgeleitet:dji:osmo-pocket-3", hersteller: "DJI", modell: "Osmo Pocket 3", kategorie: 'Cameras', datenblattUrl: "https://www.dji.com/osmo-pocket-3/specs" },
  { id: "abgeleitet:insta360:x4", hersteller: "Insta360", modell: "X4", kategorie: 'Cameras', datenblattUrl: "https://onlinemanual.insta360.com/x4/en-us/specs/hardware" },
  { id: "d82a344a-ba04-4b38-99da-fb7aa1df9a39", hersteller: "Sony", modell: "PXW-Z280", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/handheld-camcorders/pxw-z280" },
  { id: "abgeleitet:canon:xa60", hersteller: "Canon", modell: "XA60", kategorie: 'Cameras', datenblattUrl: "https://en.canon-cna.com/video-cameras/xa60b/" },
  { id: "abgeleitet:panasonic:hc-x2", hersteller: "Panasonic", modell: "HC-X2", kategorie: 'Cameras', datenblattUrl: "https://www.panasonic.com/my/consumer/camera-camcorder/camcorder/4k-full-hd-camcorder/hc-x2.specs.html" },
  { id: "abgeleitet:panasonic:ag-cx10", hersteller: "Panasonic", modell: "AG-CX10", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/ag-cx10/" },
  { id: "abgeleitet:kinefinity:terra-4k", hersteller: "Kinefinity", modell: "TERRA 4K", kategorie: 'Cameras', datenblattUrl: "https://kinefinity.com/terra/" },
  { id: "abgeleitet:red:v-raptor-xl-8k-vv", hersteller: "RED", modell: "V-RAPTOR XL 8K VV", kategorie: 'Cameras', datenblattUrl: "https://docs.red.com/955-0203/955-0203_V1.3+Rev-B+RED+PS,+V-RAPTOR+XL+8K+VV+Operation+Guide+HTML/Content/C_TechSpecs/Specs_V-RAPTOR_XL.htm" },
  { id: "abgeleitet:arri:alexa-65", hersteller: "ARRI", modell: "ALEXA 65", kategorie: 'Cameras', datenblattUrl: "https://www.arrirental.com/en/cameras/digital-65-mm-cameras/alexa-65" },
  { id: "abgeleitet:blackmagic:cinema-camera-6k-l", hersteller: "Blackmagic", modell: "Cinema Camera 6K L", kategorie: 'Cameras', datenblattUrl: "https://www.blackmagicdesign.com/products/blackmagiccinemacamera/techspecs" },
  { id: "abgeleitet:sony:a7c", hersteller: "Sony", modell: "A7C", kategorie: 'Cameras', datenblattUrl: "https://www.sony.co.uk/electronics/support/e-mount-body-ilce-7-series/ilce-7c/specifications" },
  { id: "abgeleitet:sony:a7r-iii", hersteller: "Sony", modell: "A7R III", kategorie: 'Cameras', datenblattUrl: "https://www.sony.co.uk/electronics/interchangeable-lens-cameras/ilce-7rm3/specifications" },
  { id: "abgeleitet:sony:a6100", hersteller: "Sony", modell: "A6100", kategorie: 'Cameras', datenblattUrl: "https://www.sony.co.uk/electronics/interchangeable-lens-cameras/ilce-6100/specifications" },
  { id: "abgeleitet:sony:a6300", hersteller: "Sony", modell: "A6300", kategorie: 'Cameras', datenblattUrl: "https://www.sony.co.uk/electronics/support/e-mount-body-ilce-6000-series/ilce-6300/specifications" },
  { id: "abgeleitet:sony:zv-e10-ii", hersteller: "Sony", modell: "ZV-E10 II", kategorie: 'Cameras', datenblattUrl: "https://www.sony.co.uk/electronics/support/e-mount-body-zv-e-series/zv-e10m2/specifications" },
  { id: "abgeleitet:canon:eos-r50", hersteller: "Canon", modell: "EOS R50", kategorie: 'Cameras', datenblattUrl: "https://www.canon.co.uk/cameras/eos-r50/specifications/" },
  { id: "abgeleitet:canon:eos-r100", hersteller: "Canon", modell: "EOS R100", kategorie: 'Cameras', datenblattUrl: "https://en.canon-cna.com/cameras/eos-r100/specifications/" },
  { id: "abgeleitet:canon:eos-m50-mark-ii", hersteller: "Canon", modell: "EOS M50 Mark II", kategorie: 'Cameras', datenblattUrl: "https://www.canon-europe.com/cameras/eos-m50-mark-ii/specifications/" },
  { id: "abgeleitet:canon:eos-5d-mark-iv", hersteller: "Canon", modell: "EOS 5D Mark IV", kategorie: 'Cameras', datenblattUrl: "https://www.canon.co.uk/cameras/eos-5d-mark-iv/specifications/" },
  { id: "abgeleitet:nikon:z30", hersteller: "Nikon", modell: "Z30", kategorie: 'Cameras', datenblattUrl: "https://imaging.nikon.com/imaging/lineup/mirrorless/z_30/" },
  { id: "abgeleitet:nikon:zfc", hersteller: "Nikon", modell: "Zfc", kategorie: 'Cameras', datenblattUrl: "https://imaging.nikon.com/imaging/lineup/mirrorless/z_fc/" },
  { id: "abgeleitet:nikon:z7", hersteller: "Nikon", modell: "Z7", kategorie: 'Cameras', datenblattUrl: "https://imaging.nikon.com/imaging/lineup/mirrorless/z_7/" },
  { id: "abgeleitet:nikon:z6", hersteller: "Nikon", modell: "Z6", kategorie: 'Cameras', datenblattUrl: "https://imaging.nikon.com/imaging/lineup/mirrorless/z_6/" },
  { id: "abgeleitet:panasonic:lumix-g100", hersteller: "Panasonic", modell: "Lumix G100", kategorie: 'Cameras', datenblattUrl: "https://www.panasonic.com/uk/consumer/cameras-camcorders/lumix-mirrorless-cameras/lumix-g-cameras/dc-g100.specs.html" },
  { id: "abgeleitet:panasonic:lumix-gh5s", hersteller: "Panasonic", modell: "Lumix GH5S", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/features-and-specifications-lumix-g-series-dc-gh5s/" },
  { id: "abgeleitet:fujifilm:x-t4", hersteller: "Fujifilm", modell: "X-T4", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/x-t4/specifications/" },
  { id: "abgeleitet:fujifilm:x-t50", hersteller: "Fujifilm", modell: "X-T50", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/x-t50/specifications/" },
  { id: "abgeleitet:fujifilm:x-pro3", hersteller: "Fujifilm", modell: "X-Pro3", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/x-pro3/specifications/" },
  { id: "abgeleitet:fujifilm:gfx50s-ii", hersteller: "Fujifilm", modell: "GFX50S II", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/gfx50s-ii/specifications/" },
  { id: "abgeleitet:sony:hxc-fb75", hersteller: "Sony", modell: "HXC-FB75", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/en_GB/products/4k-and-hd-camera-systems/hxc-fb75kc" },
  { id: "abgeleitet:grass-valley:ldx-135-compact", hersteller: "Grass Valley", modell: "LDX 135 Compact", kategorie: 'Cameras', datenblattUrl: "https://www.grassvalley.com/products/cameras/ldx-100-series/ldx-c135/" },
  { id: "abgeleitet:grass-valley:ldx-c135", hersteller: "Grass Valley", modell: "LDX C135", kategorie: 'Cameras', datenblattUrl: "https://www.grassvalley.com/products/cameras/ldx-100-series/ldx-c135/" },
  { id: "abgeleitet:ikegami:uhk-430s", hersteller: "Ikegami", modell: "UHK-430S", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.com/product/detail/765/" },
  { id: "abgeleitet:ikegami:hdk-73a", hersteller: "Ikegami", modell: "HDK-73A", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.de/hdk-73.html" },
  { id: "abgeleitet:aver:tr335", hersteller: "AVer", modell: "TR335", kategorie: 'Cameras', datenblattUrl: "https://www.averusa.com/products/ptz-camera/tr335" },
  { id: "abgeleitet:lumens:vc-tr60a", hersteller: "Lumens", modell: "VC-TR60A", kategorie: 'Cameras', datenblattUrl: "https://www.mylumens.com/en/Products_detail/1128/VC-TR60A-4K-Dual-Lens-Speaker-Tracking-Camera" },
  { id: "abgeleitet:ptzoptics:move-4k-20x", hersteller: "PTZOptics", modell: "Move 4K 20x", kategorie: 'Cameras', datenblattUrl: "https://ptzoptics.com/ptz-cameras/move-4k-20x" },
  { id: "abgeleitet:birddog:maki-4k", hersteller: "BirdDog", modell: "Maki 4K", kategorie: 'Cameras', datenblattUrl: "https://birddog.tv/makiultra-overview/" },
  { id: "abgeleitet:panasonic:aw-ue40", hersteller: "Panasonic", modell: "AW-UE40", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-ue50-40/" },
  { id: "abgeleitet:marshall:cv503-wp-ip67", hersteller: "Marshall", modell: "CV503-WP (IP67)", kategorie: 'Cameras', datenblattUrl: "https://marshall-usa.com/discontinued/cameras/CV503-WP.php" },
  { id: "abgeleitet:marshall:cv504", hersteller: "Marshall", modell: "CV504", kategorie: 'Cameras', datenblattUrl: "https://marshall-usa.com/cameras/CV504/" },
  { id: "abgeleitet:arri:alexa-classic", hersteller: "ARRI", modell: "ALEXA Classic", kategorie: 'Cameras', datenblattUrl: "https://www.arri.com/resource/blob/75886/2653b2727b6204327852e34f0eb5344b/1-2-3-alexa-classic-data.pdf" },
  { id: "abgeleitet:arri:alexa-xt", hersteller: "ARRI", modell: "ALEXA XT", kategorie: 'Cameras', datenblattUrl: "https://www.arri.com/resource/blob/75900/97c70e90a0405b944074526d4a5979f8/1-1-0-camera-product-comparison-alexa-alexa-xt-data.pdf" },
  { id: "abgeleitet:arri:alexa-sxt-w", hersteller: "ARRI", modell: "ALEXA SXT W", kategorie: 'Cameras', datenblattUrl: "https://www.arri.com/en/cine-systems/cine-cameras/legacy-cine-cameras/alexa-sxt-w" },
  { id: "abgeleitet:arri:alexa-mini", hersteller: "ARRI", modell: "ALEXA Mini", kategorie: 'Cameras', datenblattUrl: "https://www.arri.com/en/cine-systems/cine-cameras/legacy-cine-cameras/alexa-mini" },
  { id: "abgeleitet:arri:alexa-studio", hersteller: "ARRI", modell: "ALEXA Studio", kategorie: 'Cameras', datenblattUrl: "https://www.arri.com/resource/blob/75874/49bb65f1e663a9442ef01fb47c722210/1-3-0-alexa-studio-data.pdf" },
  { id: "abgeleitet:red:epic-dragon", hersteller: "RED", modell: "EPIC Dragon", kategorie: 'Cameras', datenblattUrl: "https://docs.red.com/955-0156/EPICSCARLETOperationGuide/en-us/Content/A_TechSpecs/Specs_EPIC_DRAGON.htm" },
  { id: "abgeleitet:red:scarlet-w", hersteller: "RED", modell: "SCARLET-W", kategorie: 'Cameras', datenblattUrl: "https://docs.red.com/955-0116_v7.4/SCARLET_DRAGON_7_4/en-us/Content/A_TechSpecs/Specs_SW_5K.htm" },
  { id: "abgeleitet:red:epic-w-helium-8k", hersteller: "RED", modell: "EPIC-W Helium 8K", kategorie: 'Cameras', datenblattUrl: "https://docs.red.com/955-0155_v7.0/WEAPONEPICWOperationGuide/en-us/Content/A_TechSpecs/Specs_EPIC-W_8KS35.htm" },
  { id: "abgeleitet:red:raven-4-5k", hersteller: "RED", modell: "RAVEN 4.5K", kategorie: 'Cameras', datenblattUrl: "https://docs.red.com/955-0154/REDRAVENOperationGuide/en-us/Content/A_TechSpecs/Specs_RAVEN.htm" },
  { id: "abgeleitet:red:weapon-8k-vv-monstro", hersteller: "RED", modell: "WEAPON 8K VV Monstro", kategorie: 'Cameras', datenblattUrl: "https://docs.red.com/955-0160/WEAPONMONSTRO8KVVOperationGuide/en-us/Content/A_TechSpecs/Specs_DSMC2_MONSTRO.htm" },
  { id: "abgeleitet:sony:f65-cinealta", hersteller: "Sony", modell: "F65 CineAlta", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/digital-cinema-cameras/f65" },
  { id: "abgeleitet:sony:f35-cinealta", hersteller: "Sony", modell: "F35 CineAlta", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/s3/cms-static-content/file/09/1237485327609.pdf" },
  { id: "abgeleitet:sony:pmw-f3", hersteller: "Sony", modell: "PMW-F3", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/en_CY/products/handheld-camcorders/pmw-f3l" },
  { id: "abgeleitet:sony:nex-fs700", hersteller: "Sony", modell: "NEX-FS700", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/en_BD/products/handheld-camcorders/nex-fs700" },
  { id: "abgeleitet:sony:nex-fs100", hersteller: "Sony", modell: "NEX-FS100", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/en_EC/products/handheld-camcorders/nex-fs100n" },
  { id: "abgeleitet:sony:pxw-fs5-ii", hersteller: "Sony", modell: "PXW-FS5 II", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/en_LU/products/handheld-camcorders/pxw-fs5m2" },
  { id: "abgeleitet:panasonic:varicam-aj-hdc27", hersteller: "Panasonic", modell: "VariCam (AJ-HDC27)", kategorie: 'Cameras' },
  { id: "abgeleitet:panasonic:ag-af101", hersteller: "Panasonic", modell: "AG-AF101", kategorie: 'Cameras', datenblattUrl: "https://www.bhphotovideo.com/c/product/731509-REG/Panasonic_AG_AF100_AG_AF100_Micro_Four_Thirds.html" },
  { id: "abgeleitet:canon:eos-c300", hersteller: "Canon", modell: "EOS C300", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/cesc821.html" },
  { id: "abgeleitet:canon:eos-c300-mark-ii", hersteller: "Canon", modell: "EOS C300 Mark II", kategorie: 'Cameras', datenblattUrl: "https://downloads.canon.com/nw/camera/products/cinema-eos/c300-mark-ii/specifications/canon-cinema-eos-c300-mark-ii-specifications-chart.pdf" },
  { id: "abgeleitet:canon:eos-c100-mark-ii", hersteller: "Canon", modell: "EOS C100 Mark II", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/cesc825.html" },
  { id: "abgeleitet:canon:eos-c500-klassiker", hersteller: "Canon", modell: "EOS C500 (Klassiker)", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/cesc822.html" },
  { id: "abgeleitet:canon:eos-c700-ff", hersteller: "Canon", modell: "EOS C700 FF", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/cesc875.html" },
  { id: "abgeleitet:canon:me20f-sh-ultra-low-light", hersteller: "Canon", modell: "ME20F-SH (Ultra-Low-Light)", kategorie: 'Cameras', datenblattUrl: "https://www.usa.canon.com/shop/p/me20f-sh" },
  { id: "abgeleitet:sony:hdc-2500", hersteller: "Sony", modell: "HDC-2500", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/en_JM/products/4k-and-hd-camera-systems/hdc-2500" },
  { id: "abgeleitet:sony:hdc-1700", hersteller: "Sony", modell: "HDC-1700", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/4k-and-hd-camera-systems/hdc-1700" },
  { id: "abgeleitet:sony:hxc-d70", hersteller: "Sony", modell: "HXC-D70", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/s3/cms-static-content/file/33/1237486957233.pdf" },
  { id: "abgeleitet:grass-valley:ldx-86-universe", hersteller: "Grass Valley", modell: "LDX 86 Universe", kategorie: 'Cameras', datenblattUrl: "https://wwwapps.grassvalley.com/docs/DataSheets/cameras/ldx/LDX_Series_DS-PUB-2-0161F-EN.pdf" },
  { id: "abgeleitet:hitachi:sk-hd1000", hersteller: "Hitachi", modell: "SK-HD1000", kategorie: 'Cameras', datenblattUrl: "https://www.hitachi-kokusai.co.jp/global/en/products/broadcast/camera/hd/sk-hd1000/sk-hd1000_s.html" },
  { id: "abgeleitet:ikegami:hdk-97a", hersteller: "Ikegami", modell: "HDK-97A", kategorie: 'Cameras', datenblattUrl: "https://www.ikegami.com/product/detail/1012/" },
  { id: "abgeleitet:panasonic:ak-hc3500", hersteller: "Panasonic", modell: "AK-HC3500", kategorie: 'Cameras', datenblattUrl: "https://www.panasonic.com/in/business/broadcast/studio-camera-systems/ak-hc3500.html" },
  { id: "abgeleitet:grass-valley:ldk-8000", hersteller: "Grass Valley", modell: "LDK 8000", kategorie: 'Cameras', datenblattUrl: "https://wwwapps.grassvalley.com/docs/Manuals/cameras/ldk8000/3922-496-31341.v01.b501.pdf" },
  { id: "abgeleitet:obsbot:tail-air", hersteller: "OBSBOT", modell: "Tail Air", kategorie: 'Cameras', datenblattUrl: "https://www.obsbot.com/obsbot-tail-air-streaming-camera" },
  { id: "abgeleitet:obsbot:tiny-2", hersteller: "OBSBOT", modell: "Tiny 2", kategorie: 'Cameras', datenblattUrl: "https://www.obsbot.com/obsbot-tiny-2-4k-webcam/specs" },
  { id: "abgeleitet:obsbot:tiny-2-lite", hersteller: "OBSBOT", modell: "Tiny 2 Lite", kategorie: 'Cameras', datenblattUrl: "https://www.obsbot.com/obsbot-tiny-2-lite-4k-webcam/specs" },
  { id: "abgeleitet:obsbot:tiny-se", hersteller: "OBSBOT", modell: "Tiny SE", kategorie: 'Cameras', datenblattUrl: "https://www.obsbot.com/obsbot-tiny-se-full-hd-webcam/specs" },
  { id: "abgeleitet:logitech:mx-brio", hersteller: "Logitech", modell: "MX Brio", kategorie: 'Cameras', datenblattUrl: "https://www.logitech.com/en-us/shop/p/mx-brio-4k-webcam" },
  { id: "abgeleitet:logitech:rally-camera", hersteller: "Logitech", modell: "Rally Camera", kategorie: 'Cameras', datenblattUrl: "https://www.logitech.com/en-us/products/video-conferencing/conference-cameras/rally-ultra-hd-ptz-camera.html" },
  { id: "abgeleitet:logitech:brio-4k", hersteller: "Logitech", modell: "Brio 4K", kategorie: 'Cameras', datenblattUrl: "https://www.logitech.com/en-us/products/webcams/brio-4k-hdr-webcam.html" },
  { id: "abgeleitet:poly:studio-e70", hersteller: "Poly", modell: "Studio E70", kategorie: 'Cameras', datenblattUrl: "https://www.poly.com/content/dam/www/products/video/studio/studio-e70/doc/poly-studio-e70-ds-en.pdf" },
  { id: "abgeleitet:huddly:l1", hersteller: "Huddly", modell: "L1", kategorie: 'Cameras', datenblattUrl: "https://www.huddly.com/conference-cameras/l1/" },
  { id: "abgeleitet:insta360:link-2", hersteller: "Insta360", modell: "Link 2", kategorie: 'Cameras', datenblattUrl: "https://www.insta360.com/product/insta360-link2" },
  { id: "abgeleitet:elgato:facecam-mk-2", hersteller: "Elgato", modell: "Facecam MK.2", kategorie: 'Cameras', datenblattUrl: "https://www.elgato.com/us/en/explorer/products/camera/facecam-mk2-rethink-what-a-webcam-can-do/" },
  { id: "abgeleitet:avermedia:pw515", hersteller: "AVerMedia", modell: "PW515", kategorie: 'Cameras', datenblattUrl: "https://www.avermedia.com/product-detail/PW515" },
  { id: "abgeleitet:panasonic:aw-ue160w", hersteller: "Panasonic", modell: "AW-UE160W", kategorie: 'Cameras', datenblattUrl: "https://pro-av.panasonic.net/en/products/aw-ue160/spec.html" },
  { id: "abgeleitet:sony:srg-x40uh", hersteller: "Sony", modell: "SRG-X40UH", kategorie: 'Cameras', datenblattUrl: "https://pro.sony/ue_US/products/ptz-network-cameras/srg-x40uh" },
  { id: "abgeleitet:lumens:vc-a51s", hersteller: "Lumens", modell: "VC-A51S", kategorie: 'Cameras', datenblattUrl: "https://www.mylumens.com/en/Products_detail/20/VC-A51S" },
  { id: "abgeleitet:lumens:vc-a71p", hersteller: "Lumens", modell: "VC-A71P", kategorie: 'Cameras', datenblattUrl: "https://www.mylumens.com/en/Products_detail/42/VC-A71P-4K-PTZ-Camera" },
  { id: "abgeleitet:avonic:cm93-ndi", hersteller: "Avonic", modell: "CM93-NDI", kategorie: 'Cameras', datenblattUrl: "https://avonic.com/cm93/" },
  { id: "abgeleitet:avonic:cm70-ndi", hersteller: "Avonic", modell: "CM70-NDI", kategorie: 'Cameras', datenblattUrl: "https://avonic.com/cm70-series/" },
  { id: "abgeleitet:ptzoptics:move-4k-12x", hersteller: "PTZOptics", modell: "Move 4K 12x", kategorie: 'Cameras', datenblattUrl: "https://ptzoptics.com/ptz-cameras/move-4k-12x" },
  { id: "abgeleitet:ptzoptics:studio-pro", hersteller: "PTZOptics", modell: "Studio Pro", kategorie: 'Cameras', datenblattUrl: "https://docs.ptzoptics.com/docs/cameras/g2-legacy/studio-pro" },
  { id: "abgeleitet:birddog:p200", hersteller: "BirdDog", modell: "P200", kategorie: 'Cameras', datenblattUrl: "https://birddog.tv/p200-overview/p200-techspecs/" },
  { id: "abgeleitet:birddog:p120", hersteller: "BirdDog", modell: "P120", kategorie: 'Cameras', datenblattUrl: "https://birddog.tv/p110p120-overview/" },
  { id: "abgeleitet:panasonic:aw-he38", hersteller: "Panasonic", modell: "AW-HE38", kategorie: 'Cameras', datenblattUrl: "https://eu.connect.panasonic.com/global/en/broadcast-proav/aw-he38h" },
  { id: "abgeleitet:sony:rx100-vii", hersteller: "Sony", modell: "RX100 VII", kategorie: 'Cameras', datenblattUrl: "https://helpguide.sony.net/dsc/1920/v1/en/contents/TP0002392811.html" },
  { id: "abgeleitet:sony:zv-1", hersteller: "Sony", modell: "ZV-1", kategorie: 'Cameras', datenblattUrl: "https://helpguide.sony.net/dc/1910/v1/en/contents/TP0002928649.html" },
  { id: "abgeleitet:sony:rx0-ii", hersteller: "Sony", modell: "RX0 II", kategorie: 'Cameras', datenblattUrl: "https://helpguide.sony.net/dsc/1910/v1/en/contents/TP0002240270.html" },
  { id: "abgeleitet:canon:powershot-v10", hersteller: "Canon", modell: "PowerShot V10", kategorie: 'Cameras', datenblattUrl: "https://support.usa.canon.com/kb/index?page=content&id=ART183827" },
  { id: "abgeleitet:panasonic:lumix-lx100-ii", hersteller: "Panasonic", modell: "Lumix LX100 II", kategorie: 'Cameras', datenblattUrl: "https://help.na.panasonic.com/answers/features-and-specifications-lumix-point-shoot-dc-lx100m2/" },
  { id: "abgeleitet:dji:osmo-action-5-pro", hersteller: "DJI", modell: "Osmo Action 5 Pro", kategorie: 'Cameras', datenblattUrl: "https://www.dji.com/osmo-action-5-pro/specs" },
  { id: "abgeleitet:gopro:hero11-black", hersteller: "GoPro", modell: "HERO11 Black", kategorie: 'Cameras', datenblattUrl: "https://gopro.com/en/us/shop/cameras/hero11-black/CHDHX-111-master.html" },
  { id: "abgeleitet:insta360:ace-pro", hersteller: "Insta360", modell: "Ace Pro", kategorie: 'Cameras', datenblattUrl: "https://onlinemanual.insta360.com/acepro/en-us/specs/hardware-aceseries" },
  { id: "abgeleitet:insta360:x3", hersteller: "Insta360", modell: "X3", kategorie: 'Cameras', datenblattUrl: "https://onlinemanual.insta360.com/x3/en-us/faq/specs/hardware" },
  { id: "abgeleitet:canon:eos-6d-mark-ii", hersteller: "Canon", modell: "EOS 6D Mark II", kategorie: 'Cameras', datenblattUrl: "https://asia.canon/en/support/6200470100" },
  { id: "abgeleitet:canon:eos-80d", hersteller: "Canon", modell: "EOS 80D", kategorie: 'Cameras', datenblattUrl: "https://my.canon/en/support/6200320100" },
  { id: "abgeleitet:canon:eos-1d-x-mark-ii", hersteller: "Canon", modell: "EOS-1D X Mark II", kategorie: 'Cameras', datenblattUrl: "https://global.canon/en/c-museum/product/dslr846.html" },
  { id: "abgeleitet:nikon:d780", hersteller: "Nikon", modell: "D780", kategorie: 'Cameras', datenblattUrl: "https://onlinemanual.nikonimglib.com/d780/en/16_technical_notes_08.html" },
  { id: "abgeleitet:nikon:d500", hersteller: "Nikon", modell: "D500", kategorie: 'Cameras', datenblattUrl: "https://imaging.nikon.com/imaging/lineup/dslr/d500/" },
  { id: "abgeleitet:nikon:d6", hersteller: "Nikon", modell: "D6", kategorie: 'Cameras', datenblattUrl: "https://onlinemanual.nikonimglib.com/d6/en/18_technical_notes_09.html" },
  { id: "abgeleitet:pentax:k-1-mark-ii", hersteller: "Pentax", modell: "K-1 Mark II", kategorie: 'Cameras', datenblattUrl: "https://us.ricoh-imaging.com/product/pentax-k-1-ii/" },
  { id: "abgeleitet:hasselblad:x2d-100c", hersteller: "Hasselblad", modell: "X2D 100C", kategorie: 'Cameras', datenblattUrl: "https://www.hasselblad.com/x-system/x2d-100c/" },
  { id: "abgeleitet:hasselblad:907x-cfv-100c", hersteller: "Hasselblad", modell: "907X & CFV 100C", kategorie: 'Cameras', datenblattUrl: "https://www.hasselblad.com/v-system/907x-cfv-100c/" },
  { id: "abgeleitet:phase-one:xt-iq4", hersteller: "Phase One", modell: "XT / IQ4", kategorie: 'Cameras', datenblattUrl: "https://www.phaseone.com/xt-camera-2/" },
  { id: "abgeleitet:fujifilm:gfx100rf", hersteller: "Fujifilm", modell: "GFX100RF", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/gfx100rf/specifications/" },
  { id: "abgeleitet:sony:a7-klassiker", hersteller: "Sony", modell: "A7 (Klassiker)", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a7/specifications" },
  { id: "abgeleitet:sony:a7-ii", hersteller: "Sony", modell: "A7 II", kategorie: 'Cameras', datenblattUrl: "https://www.dpreview.com/products/sony/slrs/sony_a7ii/specifications" },
  { id: "abgeleitet:sony:a1-ii", hersteller: "Sony", modell: "A1 II", kategorie: 'Cameras', datenblattUrl: "https://helpguide.sony.net/ilc/2440/v1/en/contents/231h_specifications_ilc2440.html" },
  { id: "abgeleitet:canon:eos-r6-klassiker", hersteller: "Canon", modell: "EOS R6 (Klassiker)", kategorie: 'Cameras', datenblattUrl: "https://cam.start.canon/en/C004/manual/html/UG-09_Reference_0100.html" },
  { id: "abgeleitet:canon:eos-ra-astro", hersteller: "Canon", modell: "EOS Ra (Astro)", kategorie: 'Cameras', datenblattUrl: "https://en.wikipedia.org/wiki/Canon_EOS_Ra" },
  { id: "abgeleitet:fujifilm:x-h1", hersteller: "Fujifilm", modell: "X-H1", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/x-h1/specifications/" },
  { id: "abgeleitet:fujifilm:x-t3", hersteller: "Fujifilm", modell: "X-T3", kategorie: 'Cameras', datenblattUrl: "https://www.fujifilm-x.com/global/products/cameras/x-t3/specifications/" },
  { id: "abgeleitet:om-system:om-3", hersteller: "OM System", modell: "OM-3", kategorie: 'Cameras', datenblattUrl: "https://explore.omsystem.com/cameras/om-3" },
  { id: "abgeleitet:datavideo:ptc-305", hersteller: "Datavideo", modell: "PTC-305", kategorie: 'Cameras', datenblattUrl: "https://datavideo.com/product/PTC-305" },
  { id: "abgeleitet:datavideo:ptc-145", hersteller: "Datavideo", modell: "PTC-145", kategorie: 'Cameras', datenblattUrl: "https://datavideo.com/product/PTC-145" },
  { id: "abgeleitet:avonic:cm93-ip", hersteller: "Avonic", modell: "CM93-IP", kategorie: 'Cameras', datenblattUrl: "https://avonic.com/cm93/" },
  { id: "abgeleitet:sony:srg-xb25", hersteller: "Sony", modell: "SRG-XB25", kategorie: 'Cameras' },
  { id: "abgeleitet:canon:cr-n300-wei", hersteller: "Canon", modell: "CR-N300 (weiß)", kategorie: 'Cameras' },
  { id: "abgeleitet:ptzoptics:move-4k-sdi", hersteller: "PTZOptics", modell: "Move 4K SDI", kategorie: 'Cameras', datenblattUrl: "https://docs.ptzoptics.com/docs/cameras/move-4k/technical-specs" },
  { id: "abgeleitet:lumens:vc-b11u", hersteller: "Lumens", modell: "VC-B11U", kategorie: 'Cameras', datenblattUrl: "https://www.mylumens.com/en/Products_detail/1047/VC-B11U-Video-Conference-Camera" },
  { id: "abgeleitet:marshall:cv730-ndi", hersteller: "Marshall", modell: "CV730-NDI", kategorie: 'Cameras', datenblattUrl: "https://marshall-usa.com/cameras/CV730-NDI/" },
  { id: "abgeleitet:aida:uhd-100a", hersteller: "AIDA", modell: "UHD-100A", kategorie: 'Cameras' },
  { id: "abgeleitet:aida:ptz4k-ndi-x30", hersteller: "AIDA", modell: "PTZ4K-NDI-X30", kategorie: 'Cameras' },
  { id: "abgeleitet:marshall:cv568", hersteller: "Marshall", modell: "CV568", kategorie: 'Cameras', datenblattUrl: "https://marshall-usa.com/cameras/CV568/" },
]
