// ───────────────────────────────────────────────────────────────────────────
// ERZEUGT von scripts/katalog-erzeugen.mjs aus
// apps/light-planner/src/core/fixtureLibrary.ts — NICHT von Hand aendern.
//
// Nur die IDENTITAET: Id, Hersteller, Modell, Kategorie. Lichtstrom,
// Abstrahlwinkel, Photometrie und Bauform bleiben im Licht-Planer — sie
// versteht sonst niemand.
//
// OHNE DATENBLATT-LINK, weil die Bibliothek keinen fuehrt. Das ist eine
// Aussage: `ohneBeleg` zaehlt diese 84 Eintraege.
//
// `npm run katalog:parity` besteht darauf, dass diese Datei noch aus jener
// stammt.
// ───────────────────────────────────────────────────────────────────────────
import type { TypEingabe } from './typ'

/** 84 Leuchtenmodelle aus der Bibliothek des Licht-Planers. */
export const LICHT_TYPEN: readonly TypEingabe[] = [
  { id: "abgeleitet:etc:source-four-19", hersteller: "ETC", modell: "Source Four 19°", kategorie: 'Lights' },
  { id: "abgeleitet:etc:source-four-26", hersteller: "ETC", modell: "Source Four 26°", kategorie: 'Lights' },
  { id: "abgeleitet:etc:source-four-36", hersteller: "ETC", modell: "Source Four 36°", kategorie: 'Lights' },
  { id: "abgeleitet:etc:source-four-50", hersteller: "ETC", modell: "Source Four 50°", kategorie: 'Lights' },
  { id: "abgeleitet:etc:source-four-zoom-15-30", hersteller: "ETC", modell: "Source Four Zoom 15–30°", kategorie: 'Lights' },
  { id: "abgeleitet:etc:source-four-zoom-25-50", hersteller: "ETC", modell: "Source Four Zoom 25–50°", kategorie: 'Lights' },
  { id: "abgeleitet:etc:source-four-led-s3", hersteller: "ETC", modell: "Source Four LED S3", kategorie: 'Lights' },
  { id: "abgeleitet:robert-juliat:714sx2-suiveur-2-5kw", hersteller: "Robert Juliat", modell: "714SX2 Suiveur 2,5kW", kategorie: 'Lights' },
  { id: "abgeleitet:generic:1-kw-fresnel", hersteller: "Generic", modell: "1 kW Fresnel", kategorie: 'Lights' },
  { id: "abgeleitet:generic:2-kw-fresnel", hersteller: "Generic", modell: "2 kW Fresnel", kategorie: 'Lights' },
  { id: "abgeleitet:etc:colorsource-fresnel", hersteller: "ETC", modell: "ColorSource Fresnel", kategorie: 'Lights' },
  { id: "abgeleitet:generic:par64-cp62-nsp", hersteller: "Generic", modell: "PAR64 CP62 (NSP)", kategorie: 'Lights' },
  { id: "abgeleitet:generic:par64-cp61-mfl", hersteller: "Generic", modell: "PAR64 CP61 (MFL)", kategorie: 'Lights' },
  { id: "abgeleitet:generic:par64-cp60-wfl", hersteller: "Generic", modell: "PAR64 CP60 (WFL)", kategorie: 'Lights' },
  { id: "abgeleitet:generic:par56-mfl-300w", hersteller: "Generic", modell: "PAR56 MFL 300W", kategorie: 'Lights' },
  { id: "abgeleitet:adj:mega-hex-par", hersteller: "ADJ", modell: "Mega HEX Par", kategorie: 'Lights' },
  { id: "abgeleitet:chauvet-professional:colordash-par-h18ip", hersteller: "Chauvet Professional", modell: "COLORdash Par H18IP", kategorie: 'Lights' },
  { id: "abgeleitet:elation:sixpar-300", hersteller: "Elation", modell: "SixPar 300", kategorie: 'Lights' },
  { id: "abgeleitet:generic:led-par-54-3-w-rgbw", hersteller: "Generic", modell: "LED PAR 54×3 W RGBW", kategorie: 'Lights' },
  { id: "abgeleitet:etc:colorsource-par", hersteller: "ETC", modell: "ColorSource PAR", kategorie: 'Lights' },
  { id: "abgeleitet:martin-harman:mac-aura-xb", hersteller: "Martin / Harman", modell: "MAC Aura XB", kategorie: 'Lights' },
  { id: "abgeleitet:robe:robin-600-ledwash", hersteller: "Robe", modell: "Robin 600 LEDWash", kategorie: 'Lights' },
  { id: "abgeleitet:robe:robin-ledbeam-150", hersteller: "Robe", modell: "Robin LEDBeam 150", kategorie: 'Lights' },
  { id: "abgeleitet:chauvet-professional:rogue-r2-wash", hersteller: "Chauvet Professional", modell: "Rogue R2 Wash", kategorie: 'Lights' },
  { id: "abgeleitet:martin-harman:mac-aura-pxl", hersteller: "Martin / Harman", modell: "MAC Aura PXL", kategorie: 'Lights' },
  { id: "abgeleitet:glp:impression-x4", hersteller: "GLP", modell: "impression X4", kategorie: 'Lights' },
  { id: "abgeleitet:robe:robin-spiider", hersteller: "Robe", modell: "Robin Spiider", kategorie: 'Lights' },
  { id: "abgeleitet:martin-harman:mac-viper-profile", hersteller: "Martin / Harman", modell: "MAC Viper Profile", kategorie: 'Lights' },
  { id: "abgeleitet:robe:robin-t1-profile", hersteller: "Robe", modell: "Robin T1 Profile", kategorie: 'Lights' },
  { id: "abgeleitet:chauvet-professional:maverick-mk3-profile", hersteller: "Chauvet Professional", modell: "Maverick MK3 Profile", kategorie: 'Lights' },
  { id: "abgeleitet:ayrton:ghibli", hersteller: "Ayrton", modell: "Ghibli", kategorie: 'Lights' },
  { id: "abgeleitet:ayrton:diablo", hersteller: "Ayrton", modell: "Diablo", kategorie: 'Lights' },
  { id: "abgeleitet:ayrton:khamsin-s", hersteller: "Ayrton", modell: "Khamsin-S", kategorie: 'Lights' },
  { id: "abgeleitet:ayrton:domino-lt", hersteller: "Ayrton", modell: "Domino LT", kategorie: 'Lights' },
  { id: "abgeleitet:ayrton:mistral", hersteller: "Ayrton", modell: "Mistral", kategorie: 'Lights' },
  { id: "abgeleitet:ayrton:perseo-profile", hersteller: "Ayrton", modell: "Perseo Profile", kategorie: 'Lights' },
  { id: "abgeleitet:ayrton:karif-lt", hersteller: "Ayrton", modell: "Karif LT", kategorie: 'Lights' },
  { id: "abgeleitet:ayrton:bora-s", hersteller: "Ayrton", modell: "Bora-S", kategorie: 'Lights' },
  { id: "abgeleitet:etc:source-four-led-series-3-lustr-x8", hersteller: "ETC", modell: "Source Four LED Series 3 Lustr X8", kategorie: 'Lights' },
  { id: "abgeleitet:etc:colorsource-spot", hersteller: "ETC", modell: "ColorSource Spot", kategorie: 'Lights' },
  { id: "abgeleitet:chauvet-professional:maverick-storm-1-wash", hersteller: "Chauvet Professional", modell: "Maverick Storm 1 Wash", kategorie: 'Lights' },
  { id: "abgeleitet:elation:proteus-maximus", hersteller: "Elation", modell: "Proteus Maximus", kategorie: 'Lights' },
  { id: "abgeleitet:robe:iforte-ltx", hersteller: "Robe", modell: "iForte LTX", kategorie: 'Lights' },
  { id: "abgeleitet:martin-harman:mac-encore-performance-cld", hersteller: "Martin / Harman", modell: "MAC Encore Performance CLD", kategorie: 'Lights' },
  { id: "abgeleitet:martin-harman:mac-aura-xip", hersteller: "Martin / Harman", modell: "MAC Aura XIP", kategorie: 'Lights' },
  { id: "abgeleitet:elation:fuze-max-profile", hersteller: "Elation", modell: "Fuze Max Profile", kategorie: 'Lights' },
  { id: "abgeleitet:sgm:p-6", hersteller: "SGM", modell: "P-6", kategorie: 'Lights' },
  { id: "abgeleitet:adj:vizi-beam-12rx", hersteller: "ADJ", modell: "Vizi Beam 12RX", kategorie: 'Lights' },
  { id: "abgeleitet:astera:ax1-pixeltube", hersteller: "Astera", modell: "AX1 PixelTube", kategorie: 'Lights' },
  { id: "abgeleitet:chauvet-professional:rogue-r2-spot", hersteller: "Chauvet Professional", modell: "Rogue R2 Spot", kategorie: 'Lights' },
  { id: "abgeleitet:chauvet-professional:colordash-par-h12x-ip", hersteller: "Chauvet Professional", modell: "COLORdash Par H12X IP", kategorie: 'Lights' },
  { id: "abgeleitet:robe:ledbeam-350", hersteller: "Robe", modell: "LEDBeam 350", kategorie: 'Lights' },
  { id: "abgeleitet:elation:kl-panel-xl", hersteller: "Elation", modell: "KL Panel XL", kategorie: 'Lights' },
  { id: "abgeleitet:adj:focus-spot-6z", hersteller: "ADJ", modell: "Focus Spot 6Z", kategorie: 'Lights' },
  { id: "abgeleitet:chauvet-professional:rogue-r1-beamwash", hersteller: "Chauvet Professional", modell: "Rogue R1 BeamWash", kategorie: 'Lights' },
  { id: "abgeleitet:cameo:opus-s5", hersteller: "Cameo", modell: "OPUS S5", kategorie: 'Lights' },
  { id: "abgeleitet:cameo:opus-h5", hersteller: "Cameo", modell: "OPUS H5", kategorie: 'Lights' },
  { id: "abgeleitet:cameo:otos-h5", hersteller: "Cameo", modell: "OTOS H5", kategorie: 'Lights' },
  { id: "abgeleitet:cameo:otos-sp6", hersteller: "Cameo", modell: "OTOS SP6", kategorie: 'Lights' },
  { id: "abgeleitet:cameo:evos-s3", hersteller: "Cameo", modell: "EVOS S3", kategorie: 'Lights' },
  { id: "abgeleitet:cameo:evos-w7", hersteller: "Cameo", modell: "EVOS W7", kategorie: 'Lights' },
  { id: "abgeleitet:cameo:otos-b5", hersteller: "Cameo", modell: "OTOS B5", kategorie: 'Lights' },
  { id: "abgeleitet:cameo:movo-beam-z100", hersteller: "Cameo", modell: "MOVO BEAM Z100", kategorie: 'Lights' },
  { id: "abgeleitet:robe:robin-megapointe", hersteller: "Robe", modell: "Robin MegaPointe", kategorie: 'Lights' },
  { id: "abgeleitet:robe:robin-pointe", hersteller: "Robe", modell: "Robin Pointe", kategorie: 'Lights' },
  { id: "abgeleitet:clay-paky:mythos-2", hersteller: "Clay Paky", modell: "Mythos 2", kategorie: 'Lights' },
  { id: "abgeleitet:clay-paky:sharpy", hersteller: "Clay Paky", modell: "Sharpy", kategorie: 'Lights' },
  { id: "abgeleitet:mole-richardson:molefay-4-lite", hersteller: "Mole-Richardson", modell: "Molefay 4-Lite", kategorie: 'Lights' },
  { id: "abgeleitet:martin-harman:atomic-3000-dmx", hersteller: "Martin / Harman", modell: "Atomic 3000 DMX", kategorie: 'Lights' },
  { id: "abgeleitet:etc:colorsource-cyc", hersteller: "ETC", modell: "ColorSource CYC", kategorie: 'Lights' },
  { id: "abgeleitet:arri:cyc-1250", hersteller: "ARRI", modell: "CYC 1250", kategorie: 'Lights' },
  { id: "abgeleitet:etc:desire-d22", hersteller: "ETC", modell: "Desire D22", kategorie: 'Lights' },
  { id: "abgeleitet:etc:desire-d40", hersteller: "ETC", modell: "Desire D40", kategorie: 'Lights' },
  { id: "abgeleitet:philips-colorkinetics:colorblast-12", hersteller: "Philips / ColorKinetics", modell: "ColorBlast 12", kategorie: 'Lights' },
  { id: "abgeleitet:robert-juliat:cyrano-2500w", hersteller: "Robert Juliat", modell: "Cyrano 2500W", kategorie: 'Lights' },
  { id: "abgeleitet:aputure:ls-600x-pro", hersteller: "Aputure", modell: "LS 600x Pro", kategorie: 'Lights' },
  { id: "abgeleitet:aputure:ls-300x-ii", hersteller: "Aputure", modell: "LS 300x II", kategorie: 'Lights' },
  { id: "abgeleitet:elation:kl-fresnel-8-fc", hersteller: "Elation", modell: "KL Fresnel 8 FC", kategorie: 'Lights' },
  { id: "abgeleitet:elation:kl-fresnel-6-fc", hersteller: "Elation", modell: "KL Fresnel 6 FC", kategorie: 'Lights' },
  { id: "abgeleitet:elation:kl-panel-fc", hersteller: "Elation", modell: "KL Panel FC", kategorie: 'Lights' },
  { id: "abgeleitet:elation:kl-profile-fc", hersteller: "Elation", modell: "KL Profile FC", kategorie: 'Lights' },
  { id: "abgeleitet:elation:kl-par-fc", hersteller: "Elation", modell: "KL PAR FC", kategorie: 'Lights' },
  { id: "abgeleitet:elation:fuze-wash-z350", hersteller: "Elation", modell: "Fuze Wash Z350", kategorie: 'Lights' },
  { id: "abgeleitet:elation:fuze-par-z120-ip", hersteller: "Elation", modell: "Fuze Par Z120 IP", kategorie: 'Lights' },
]
