// ───────────────────────────────────────────────────────────────────────────
// ERZEUGT von scripts/katalog-erzeugen.mjs aus
// apps/light-planner/src/core/fixtureLibrary.ts — NICHT von Hand aendern.
//
// Nur die IDENTITAET: Id, Hersteller, Modell, Kategorie, Datenblatt. Lichtstrom,
// Abstrahlwinkel, Photometrie und Bauform bleiben im Licht-Planer — sie
// versteht sonst niemand.
//
// Datenblatt-Link, wo das Profil einen fuehrt. 10 von 84 haben keinen;
// das ist eine Aussage: `ohneBeleg` zaehlt sie.
//
// `npm run katalog:parity` besteht darauf, dass diese Datei noch aus jener
// stammt.
// ───────────────────────────────────────────────────────────────────────────
import type { TypEingabe } from './typ'

/** 84 Leuchtenmodelle aus der Bibliothek des Licht-Planers. */
export const LICHT_TYPEN: readonly TypEingabe[] = [
  { id: "abgeleitet:etc:source-four-19", hersteller: "ETC", modell: "Source Four 19°", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737460415", quellRef: "etc-s4-19" },
  { id: "abgeleitet:etc:source-four-26", hersteller: "ETC", modell: "Source Four 26°", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737460435", quellRef: "etc-s4-26" },
  { id: "abgeleitet:etc:source-four-36", hersteller: "ETC", modell: "Source Four 36°", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737460423", quellRef: "etc-s4-36" },
  { id: "abgeleitet:etc:source-four-50", hersteller: "ETC", modell: "Source Four 50°", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737460305", quellRef: "etc-s4-50" },
  { id: "abgeleitet:etc:source-four-zoom-15-30", hersteller: "ETC", modell: "Source Four Zoom 15–30°", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737460417", quellRef: "etc-s4-zoom-15-30" },
  { id: "abgeleitet:etc:source-four-zoom-25-50", hersteller: "ETC", modell: "Source Four Zoom 25–50°", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/WorkArea/DownloadAsset.aspx?id=10737460396", quellRef: "etc-s4-zoom-25-50" },
  { id: "abgeleitet:etc:source-four-led-s3", hersteller: "ETC", modell: "Source Four LED S3", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/Products/Entertainment-Fixtures/Source-Four-LED-Series-3/Features.aspx", quellRef: "etc-s4led-s3" },
  { id: "abgeleitet:robert-juliat:714sx2", hersteller: "Robert Juliat", modell: "714SX2", kategorie: 'Lights', datenblattUrl: "https://www.robertjuliat.com/Product_Specifications/Fiches_EN/Standard/DSEN074_714SX2.pdf", quellRef: "robert-juliat-714" },
  { id: "abgeleitet:generic:1-kw-fresnel", hersteller: "Generic", modell: "1 kW Fresnel", kategorie: 'Lights', quellRef: "fresnel-1kw" },
  { id: "abgeleitet:generic:2-kw-fresnel", hersteller: "Generic", modell: "2 kW Fresnel", kategorie: 'Lights', quellRef: "fresnel-2kw" },
  { id: "abgeleitet:etc:colorsource-fresnel-v", hersteller: "ETC", modell: "ColorSource Fresnel V", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/Products/Entertainment-Fixtures/ColorSource-Fresnel-V/Features.aspx", quellRef: "etc-cs-fresnel" },
  { id: "abgeleitet:generic:par64-cp62-nsp", hersteller: "Generic", modell: "PAR64 CP62 (NSP)", kategorie: 'Lights', quellRef: "par64-cp62-nsp" },
  { id: "abgeleitet:generic:par64-cp61-mfl", hersteller: "Generic", modell: "PAR64 CP61 (MFL)", kategorie: 'Lights', quellRef: "par64-cp61-mfl" },
  { id: "abgeleitet:generic:par64-cp60-wfl", hersteller: "Generic", modell: "PAR64 CP60 (WFL)", kategorie: 'Lights', quellRef: "par64-cp60-wfl" },
  { id: "abgeleitet:generic:par56-mfl-300w", hersteller: "Generic", modell: "PAR56 MFL 300W", kategorie: 'Lights', quellRef: "par56-mfl" },
  { id: "abgeleitet:adj:mega-hex-par", hersteller: "ADJ", modell: "Mega HEX Par", kategorie: 'Lights', datenblattUrl: "https://www.adj.com/mega-hex-par", quellRef: "adj-mega-hex-par" },
  { id: "abgeleitet:chauvet-professional:colordash-par-h18-xip", hersteller: "Chauvet Professional", modell: "COLORdash PAR H18 XIP", kategorie: 'Lights', datenblattUrl: "https://chauvetprofessional.com/product/colordash-par-h18-xip/", quellRef: "chauvet-colordash-h18ip" },
  { id: "abgeleitet:elation:sixpar-300", hersteller: "Elation", modell: "SixPar 300", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/sixpar-300", quellRef: "elation-sixpar-300" },
  { id: "abgeleitet:generic:led-par-54-3-w-rgbw", hersteller: "Generic", modell: "LED PAR 54×3 W RGBW", kategorie: 'Lights', quellRef: "generic-led-par-54x3" },
  { id: "abgeleitet:etc:colorsource-par", hersteller: "ETC", modell: "ColorSource PAR", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/Products/Entertainment-Fixtures/ColorSource-PAR/Features.aspx", quellRef: "etc-cs-par" },
  { id: "abgeleitet:martin-harman:mac-aura-xb", hersteller: "Martin / Harman", modell: "MAC Aura XB", kategorie: 'Lights', datenblattUrl: "https://www.martin.com/en/products/mac-aura-xb", quellRef: "martin-mac-aura-xb" },
  { id: "abgeleitet:robe:robin-600-ledwash", hersteller: "Robe", modell: "Robin 600 LEDWash", kategorie: 'Lights', datenblattUrl: "https://cdn.aws.robe.cz/print/en_product_513.pdf", quellRef: "robe-robin-600-ledwash" },
  { id: "abgeleitet:robe:robin-ledbeam-150", hersteller: "Robe", modell: "Robin LEDBeam 150", kategorie: 'Lights', datenblattUrl: "https://www.robe.cz/ledbeam-150", quellRef: "robe-robin-ledbeam-150" },
  { id: "abgeleitet:chauvet-professional:rogue-r2-wash", hersteller: "Chauvet Professional", modell: "Rogue R2 Wash", kategorie: 'Lights', datenblattUrl: "https://www.chauvetprofessional.com/products/rogue-r2-wash/", quellRef: "chauvet-rogue-r2-wash" },
  { id: "abgeleitet:martin-harman:mac-aura-pxl", hersteller: "Martin / Harman", modell: "MAC Aura PXL", kategorie: 'Lights', datenblattUrl: "https://www.martin.com/en/products/mac-aura-pxl", quellRef: "martin-mac-aura-pxl" },
  { id: "abgeleitet:glp:impression-x4", hersteller: "GLP", modell: "impression X4", kategorie: 'Lights', datenblattUrl: "https://glp.de/en/?view=article&id=848&catid=55", quellRef: "glp-impression-x4" },
  { id: "abgeleitet:robe:robin-spiider", hersteller: "Robe", modell: "Robin Spiider", kategorie: 'Lights', datenblattUrl: "https://www.robe.cz/spiider", quellRef: "robe-robin-spiider" },
  { id: "abgeleitet:martin-harman:mac-viper-profile", hersteller: "Martin / Harman", modell: "MAC Viper Profile", kategorie: 'Lights', datenblattUrl: "https://www.martin.com/en/products/mac-viper-profile", quellRef: "martin-mac-viper-profile" },
  { id: "abgeleitet:robe:robin-t1-profile", hersteller: "Robe", modell: "Robin T1 Profile", kategorie: 'Lights', datenblattUrl: "https://www.robe.cz/t1-profile", quellRef: "robe-robin-t1-profile" },
  { id: "abgeleitet:chauvet-professional:maverick-mk3-profile", hersteller: "Chauvet Professional", modell: "Maverick MK3 Profile", kategorie: 'Lights', datenblattUrl: "https://chauvetprofessional.com/product/maverick-mk3-profile/", quellRef: "chauvet-maverick-mk3-profile" },
  { id: "abgeleitet:ayrton:ghibli", hersteller: "Ayrton", modell: "Ghibli", kategorie: 'Lights', datenblattUrl: "https://www.ayrton.eu/products/ghibli/", quellRef: "ayrton-ghibli" },
  { id: "abgeleitet:ayrton:diablo", hersteller: "Ayrton", modell: "Diablo", kategorie: 'Lights', datenblattUrl: "https://www.ayrton.eu/products/diablo/", quellRef: "ayrton-diablo" },
  { id: "abgeleitet:ayrton:khamsin-s", hersteller: "Ayrton", modell: "Khamsin-S", kategorie: 'Lights', datenblattUrl: "https://www.ayrton.eu/products/khamsin-s/", quellRef: "ayrton-khamsin" },
  { id: "abgeleitet:ayrton:domino-lt", hersteller: "Ayrton", modell: "Domino LT", kategorie: 'Lights', datenblattUrl: "https://www.ayrton.eu/products/domino-lt/", quellRef: "ayrton-domino-lt" },
  { id: "abgeleitet:ayrton:mistral", hersteller: "Ayrton", modell: "Mistral", kategorie: 'Lights', datenblattUrl: "https://www.ayrton.eu/products/mistral/", quellRef: "ayrton-mistral" },
  { id: "abgeleitet:ayrton:perseo-profile", hersteller: "Ayrton", modell: "Perseo Profile", kategorie: 'Lights', datenblattUrl: "https://www.ayrton.eu/products/perseo-profile/", quellRef: "ayrton-perseo-profile" },
  { id: "abgeleitet:ayrton:karif-lt", hersteller: "Ayrton", modell: "Karif LT", kategorie: 'Lights', datenblattUrl: "https://www.ayrton.eu/products/karif-lt/", quellRef: "ayrton-karif-lt" },
  { id: "abgeleitet:ayrton:bora-s", hersteller: "Ayrton", modell: "Bora-S", kategorie: 'Lights', datenblattUrl: "https://www.ayrton.eu/products/bora-s/", quellRef: "ayrton-bora" },
  { id: "abgeleitet:etc:source-four-led-series-3-lustr-x8", hersteller: "ETC", modell: "Source Four LED Series 3 Lustr X8", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/Products/Entertainment-Fixtures/Source-Four-LED-Series-3/Features.aspx", quellRef: "etc-s4-led-s3-lustr" },
  { id: "abgeleitet:etc:colorsource-spot", hersteller: "ETC", modell: "ColorSource Spot", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/Products/Lighting-Fixtures/ColorSource-Spot/Features.aspx", quellRef: "etc-colorsource-spot" },
  { id: "abgeleitet:chauvet-professional:maverick-storm-1-wash", hersteller: "Chauvet Professional", modell: "Maverick Storm 1 Wash", kategorie: 'Lights', datenblattUrl: "https://chauvetprofessional.com/product/maverick-storm-1-wash/", quellRef: "chauvet-maverick-storm-1-wash" },
  { id: "abgeleitet:elation:proteus-maximus", hersteller: "Elation", modell: "Proteus Maximus", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/proteus-maximus", quellRef: "elation-proteus-maximus" },
  { id: "abgeleitet:robe:iforte-ltx-wb", hersteller: "Robe", modell: "iFORTE LTX WB", kategorie: 'Lights', datenblattUrl: "https://www.robe.cz/iforte-ltx-wb", quellRef: "robe-iforte-ltx" },
  { id: "abgeleitet:martin-harman:mac-encore-performance-cld", hersteller: "Martin / Harman", modell: "MAC Encore Performance CLD", kategorie: 'Lights', datenblattUrl: "https://www.martin.com/en/products/mac-encore-performance-cld", quellRef: "martin-mac-encore-perf-cld" },
  { id: "abgeleitet:martin-harman:mac-aura-xip", hersteller: "Martin / Harman", modell: "MAC Aura XIP", kategorie: 'Lights', datenblattUrl: "https://www.martin.com/en/products/mac-aura-xip", quellRef: "martin-mac-aura-xip" },
  { id: "abgeleitet:elation:fuze-max-profile", hersteller: "Elation", modell: "Fuze Max Profile", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/fuze-max-profile", quellRef: "elation-fuze-max-profile" },
  { id: "abgeleitet:sgm:p-6", hersteller: "SGM", modell: "P-6", kategorie: 'Lights', datenblattUrl: "https://www.sgmlighting.com/products/p%c2%b76", quellRef: "sgm-p6" },
  { id: "abgeleitet:adj:vizi-beam-12rx", hersteller: "ADJ", modell: "Vizi Beam 12RX", kategorie: 'Lights', datenblattUrl: "https://www.adj.com/vizi-beam-12rx", quellRef: "adj-vizi-beam-12rx" },
  { id: "abgeleitet:astera:ax1-pixeltube", hersteller: "Astera", modell: "AX1 PixelTube", kategorie: 'Lights', datenblattUrl: "https://astera-led.com/products/ax1-pixeltube/", quellRef: "astera-ax1-pixeltube" },
  { id: "abgeleitet:chauvet-professional:rogue-r2-spot", hersteller: "Chauvet Professional", modell: "Rogue R2 Spot", kategorie: 'Lights', quellRef: "chauvet-rogue-r2-spot" },
  { id: "abgeleitet:chauvet-professional:colordash-par-h12x-ip", hersteller: "Chauvet Professional", modell: "COLORdash Par H12X IP", kategorie: 'Lights', datenblattUrl: "https://chauvetprofessional.com/product/colordash-par-h12x-ip/", quellRef: "chauvet-colordash-par-h12x" },
  { id: "abgeleitet:robe:ledbeam-350", hersteller: "Robe", modell: "LEDBeam 350", kategorie: 'Lights', datenblattUrl: "https://www.robe.cz/ledbeam-350", quellRef: "robe-ledbeam-350" },
  { id: "abgeleitet:elation:kl-panel-xl", hersteller: "Elation", modell: "KL Panel XL", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/kl-panel-xl", quellRef: "elation-kl-panel-xl" },
  { id: "abgeleitet:adj:focus-spot-6z", hersteller: "ADJ", modell: "Focus Spot 6Z", kategorie: 'Lights', datenblattUrl: "https://www.adj.com/focus-spot-6z", quellRef: "adj-focus-spot-6z" },
  { id: "abgeleitet:chauvet-professional:rogue-r1-beamwash", hersteller: "Chauvet Professional", modell: "Rogue R1 BeamWash", kategorie: 'Lights', datenblattUrl: "https://chauvetprofessional.com/product/rogue-r1-beamwash/", quellRef: "chauvet-rogue-r1-beamwash" },
  { id: "abgeleitet:cameo:opus-s5", hersteller: "Cameo", modell: "OPUS S5", kategorie: 'Lights', datenblattUrl: "https://www.cameolight.com/en/solutions/rental/moving-lights/spot-moving-heads/19890/opus-s5", quellRef: "cameo-opus-s5" },
  { id: "abgeleitet:cameo:opus-h5", hersteller: "Cameo", modell: "OPUS H5", kategorie: 'Lights', quellRef: "cameo-opus-h5" },
  { id: "abgeleitet:cameo:otos-h5", hersteller: "Cameo", modell: "OTOS H5", kategorie: 'Lights', datenblattUrl: "https://www.cameolight.com/en/series/otos-series/26039/otos-h5", quellRef: "cameo-otos-h5" },
  { id: "abgeleitet:cameo:otos-sp6", hersteller: "Cameo", modell: "OTOS SP6", kategorie: 'Lights', datenblattUrl: "https://www.cameolight.com/detail/index/sArticle/29049", quellRef: "cameo-otos-sp6" },
  { id: "abgeleitet:cameo:evos-s3", hersteller: "Cameo", modell: "EVOS S3", kategorie: 'Lights', datenblattUrl: "https://www.cameolight.com/de/downloads/file/id/1725041077", quellRef: "cameo-evos-s3" },
  { id: "abgeleitet:cameo:evos-w7", hersteller: "Cameo", modell: "EVOS W7", kategorie: 'Lights', datenblattUrl: "https://www.cameolight.com/en/solutions/rental/moving-lights/beam-moving-heads/20565/evos-w7", quellRef: "cameo-evos-w7" },
  { id: "abgeleitet:cameo:otos-b5", hersteller: "Cameo", modell: "OTOS B5", kategorie: 'Lights', datenblattUrl: "https://www.cameolight.com/detail/index/sArticle/29085", quellRef: "cameo-otos-b5" },
  { id: "abgeleitet:cameo:movo-beam-z100", hersteller: "Cameo", modell: "MOVO BEAM Z100", kategorie: 'Lights', datenblattUrl: "https://www.cameolight.com/en/solutions/dj-musicians/moving-lights/moving-heads/17232/movo-beam-z100", quellRef: "cameo-movo-beam-z100" },
  { id: "abgeleitet:robe:robin-megapointe", hersteller: "Robe", modell: "Robin MegaPointe", kategorie: 'Lights', datenblattUrl: "https://www.robe.cz/megapointe", quellRef: "robe-robin-megapointe" },
  { id: "abgeleitet:robe:robin-pointe", hersteller: "Robe", modell: "Robin Pointe", kategorie: 'Lights', datenblattUrl: "https://www.robe.cz/pointe", quellRef: "robe-robin-pointe" },
  { id: "abgeleitet:clay-paky:mythos-2", hersteller: "Clay Paky", modell: "Mythos 2", kategorie: 'Lights', quellRef: "claypaky-mythos2" },
  { id: "abgeleitet:clay-paky:sharpy", hersteller: "Clay Paky", modell: "Sharpy", kategorie: 'Lights', datenblattUrl: "https://www.claypaky.it/products/sharpy-legacy/", quellRef: "claypaky-sharpy" },
  { id: "abgeleitet:mole-richardson:molefay-4-lite", hersteller: "Mole-Richardson", modell: "Molefay 4-Lite", kategorie: 'Lights', datenblattUrl: "https://www.mole.com/5581-2600w-four-light-molefay", quellRef: "molefay-4lite" },
  { id: "abgeleitet:martin-harman:atomic-3000-dmx", hersteller: "Martin / Harman", modell: "Atomic 3000 DMX", kategorie: 'Lights', datenblattUrl: "https://www.martin.com/en/products/atomic-3000-dmx", quellRef: "martin-atomic-3000" },
  { id: "abgeleitet:etc:colorsource-cyc", hersteller: "ETC", modell: "ColorSource CYC", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/Products/Entertainment-Fixtures/ColorSource-CYC/Features.aspx", quellRef: "etc-cs-cyc" },
  { id: "abgeleitet:arri:cyc-1250", hersteller: "ARRI", modell: "CYC 1250", kategorie: 'Lights', datenblattUrl: "https://www.arri.com/resource/blob/163268/de59e7af51831095d387c69361963628/arri-cyc-flood-1250-manual-de-en-data.pdf", quellRef: "arri-cyc-1250" },
  { id: "abgeleitet:etc:desire-d22", hersteller: "ETC", modell: "Desire D22", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/Products/Entertainment-Fixtures/Desire-D22/Features.aspx", quellRef: "etc-desire-d22" },
  { id: "abgeleitet:etc:desire-d40", hersteller: "ETC", modell: "Desire D40", kategorie: 'Lights', datenblattUrl: "https://www.etcconnect.com/Products/Entertainment-Fixtures/Desire-D40/Features.aspx", quellRef: "etc-desire-d40" },
  { id: "abgeleitet:philips-colorkinetics:colorblast-12", hersteller: "Philips / ColorKinetics", modell: "ColorBlast 12", kategorie: 'Lights', datenblattUrl: "https://www.docs.colorkinetics.com/support/datasheets/ColorBlast12.pdf", quellRef: "philips-colorblast-12" },
  { id: "abgeleitet:robert-juliat:cyrano-2500w", hersteller: "Robert Juliat", modell: "Cyrano 2500W", kategorie: 'Lights', datenblattUrl: "https://www.robertjuliat.com/followspots/cyrano.html", quellRef: "robert-juliat-cyrano" },
  { id: "abgeleitet:aputure:ls-600x-pro", hersteller: "Aputure", modell: "LS 600x Pro", kategorie: 'Lights', datenblattUrl: "https://www.aputure.com/products/ls-600x-pro", quellRef: "aputure-ls-600x-pro" },
  { id: "abgeleitet:aputure:ls-300x", hersteller: "Aputure", modell: "LS 300x", kategorie: 'Lights', datenblattUrl: "https://aputure.com/en-US/products/ls-300x", quellRef: "aputure-ls-300x-ii" },
  { id: "abgeleitet:elation:kl-fresnel-8-fc", hersteller: "Elation", modell: "KL Fresnel 8 FC", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/kl-fresnel-8-fc", quellRef: "elation-kl-fresnel-8-fc" },
  { id: "abgeleitet:elation:kl-fresnel-6-fc", hersteller: "Elation", modell: "KL Fresnel 6 FC", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/kl-fresnel-6-fc", quellRef: "elation-kl-fresnel-6-fc" },
  { id: "abgeleitet:elation:kl-panel", hersteller: "Elation", modell: "KL Panel", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/products/kl-panel", quellRef: "elation-kl-panel-fc" },
  { id: "abgeleitet:elation:kl-profile-fc", hersteller: "Elation", modell: "KL Profile FC", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/products/kl-profile-fc", quellRef: "elation-kl-profile-fc" },
  { id: "abgeleitet:elation:kl-par-fc", hersteller: "Elation", modell: "KL PAR FC", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/products/kl-par-fc", quellRef: "elation-kl-par-fc" },
  { id: "abgeleitet:elation:fuze-wash-z350", hersteller: "Elation", modell: "Fuze Wash Z350", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/products/fuze-wash-z350", quellRef: "elation-fuze-wash-z350" },
  { id: "abgeleitet:elation:fuze-par-z120-ip", hersteller: "Elation", modell: "Fuze Par Z120 IP", kategorie: 'Lights', datenblattUrl: "https://www.elationlighting.com/products/fuze-par-z120-ip", quellRef: "elation-fuze-par-z120" },
]
